### PR TITLE
Fix issue 328, evaluation/typechecking inconsistency

### LINKED ISSUE #328: inconsistency in typechecking and evaluation
In typechecking, we go through the top-level definitions in order. This ensures there are no dags and matches the way a person might go through it.

When we evaluate, we take more of a graph model, and work from the bottom up. This creates in inconsistency where things typecheck, but fail at runtime, but other kinds of bugs are possible.

We should be clear what the semantics are. There are at least two questions:

1. if we shadow a Predef function later in the file, which version do we see before then? It seems like there are only two answers to this: a) error on a predef shadow, b) we see predef version. I prefer the second answer.
2. should we allow shadowing at the top level? We do in local defs, and the type-checking allows it, but such shadows are sources of bugs now.

The semantics of typechecking, to me, seem more like a human would expect. The most direct fix is probably to make those semantics the language semantics and fix evaluation.

### PR DESCRIPTION
**Pull request by johnynek**
fix #328 

This does to by explicitly evaluating the file in the order we type-check it, with the correct environment at each point.

### CODE REVIEW

**Comment by johnynek** [comment]
@snoble if you have time, take a look at this...

This removes using NameKind from Evaluation, and just directly matches the type-checking semantics with the evaluation: namely: type constructors can't be shadowed, we consider external defs first, then finally lets.

This also passes over the package one time to build a lazy graph of what is to be computed, rather than doing so many lookups (I think). It may be faster, but I haven't benchmarked.

File: core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala [hunk 1]
```diff
@@ -87,10 +87,11 @@ class TypeEnv[+A] private (
    * annotated
    */
   def addExternalValue(pack: PackageName, name: Identifier, t: Type): TypeEnv[A] =
-    new TypeEnv(constructors = constructors, definedTypes = definedTypes, values = values.updated((pack, name), t))
+    new TypeEnv(
+      constructors = constructors,
+      definedTypes = definedTypes,
+      values = values.updated((pack, name), t))
 
-  // TODO to support parameter named patterns we'd need to know the
```
Comment (johnynek) [inline core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala:92]: this todo is already done.

File: core/src/main/scala/org/bykn/bosatsu/Evaluation.scala [hunk 2]
```diff
@@ -284,18 +270,108 @@ case class Evaluation[T](pm: PackageMap.Typed[T], externals: Externals) {
...
+      .filter(_.packageName == p.name)
+      .flatMap { dt =>
+        dt.constructors.iterator.map { case (cn, _, _) =>
+          (cn, constructor(cn, dt))
+        }
+      }
+      .toMap
+  }
+
+  private def addLet(p: Package.Typed[T], env: Env, let: (Bindable, RecursionKind, TypedExpr[T])): Env = {
```
Comment (johnynek) [inline core/src/main/scala/org/bykn/bosatsu/Evaluation.scala]: p is unused.
