### PR TITLE
Fix singleton parametric constructor inference in recur matches

### LINKED ISSUE #2015: Bad type inference on matches
I have this code:

```
def uncons_step(rem: Int, current: LazyList[a], pending: List[LazyList[a]]) -> Option[(Lazy[a], LazyList[a])]:
  recur (rem, pending, current):
    case (_, _, Cons(head, tail)):
        Some((head, append_pending(tail, pending)))
    case (_, [], Empty):
        None
    case _ if cmp_Int(rem, 0) matches LT | EQ:
        None
    case (_, [next, *rest], Empty):
          uncons_step(rem, next, rest)
    case (_, pending, Concat(first, second)):
      uncons_step(rem.sub(1), first, [second, *pending])
    case (_, _, Suspend(next)):
      uncons_step(rem.sub(1), get_Lazy(next), pending)
    case (rem, [], Mapped(source, fn)):
      match uncons_step(rem, source, []):
        case Some((head, tail)):
          mapped_head = lazy(() -> fn(get_Lazy(head)))
          mapped_tail = map(tail, fn)
          Some((mapped_head, mapped_tail))
        case None: None
    case (_, [next, *rest], Mapped(source, fn)):
      match uncons_step(rem, source, []):
        case None:
          uncons_step(rem, next, rest)
        case Some((head, tail)):
          mapped_head = lazy(() -> fn(get_Lazy(head)))
          mapped_tail = map(tail, fn)
          Some((mapped_head, append_pending(mapped_tail, pending)))
    case (_, [], FlatMapped(source, fn)):
      match uncons_step(rem, source, []):
        case Some((head, tail)):
          mapped = fn(get_Lazy(head)) 
          uncons_step(rem.sub(1), mapped, [flat_map(tail, fn)])
        case None: None
    case (_, [next, *rest], FlatMapped(source, fn)):
      match uncons_step(rem.sub(1), source, []):
        case None:
          uncons_step(rem, next, rest)
        case Some((head, tail)):
          mapped = fn(get_Lazy(head)) 
          uncons_step(rem.sub(1), mapped, [flat_map(tail, fn), *pending])
```
which I expect to type check. But I get the following error:
```
oscar@mac zafu % ./bosatsu lib test

in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:93:13, package Zafu/Collection/LazyList
recursive call to uncons_step is not lexicographically smaller on recur target (rem, pending, current).
91|      uncons_step(rem.sub(1), get_Lazy(next), pending)
92|    case (rem, [], Mapped(source, fn)):
93|      match uncons_step(rem, source, []):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:100:13, package Zafu/Collection/LazyList
recursive call to uncons_step is not lexicographically smaller on recur target (rem, pending, current).
 98|        case None: None
 99|    case (_, [next, *rest], Mapped(source, fn)):
100|      match uncons_step(rem, source, []):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:108:13, package Zafu/Collection/LazyList
recursive call to uncons_step is not lexicographically smaller on recur target (rem, pending, current).
106|          Some((mapped_head, append_pending(mapped_tail, pending)))
107|    case (_, [], FlatMapped(source, fn)):
108|      match uncons_step(rem, source, []):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
These errors don't make sense to me, and look like issue number 1:

The recursion checker should accept this because the order is `(rem, pending, current)` and we are calling with `rem` and `pending` not changing but `next` is a substructure so this should be allowed. I thought it may be rejecting the fact that we wrote the literal `[]` as the pattern and `[]` as the constructor and couldn't see that those were the same. It should be able to see that those are the same. That is a bug we need to fix.

So, to work around it, I attempted to name the pattern and changed the mapped branch to:
```
    case (rem, [] as e, Mapped(source, fn)):
      match uncons_step(rem, source, e):
        case Some((head, tail)):
          mapped_head = lazy(() -> fn(get_Lazy(head)))
          mapped_tail = map(tail, fn)
          Some((mapped_head, mapped_tail))
        case None: None
```
and here is another error: 
```
in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:93:38, package Zafu/Collection/LazyList
type mismatch in call to uncons_step, argument 3 of 3:
expected: $b$51e
found: $a$50
function type: (Int, LazyList[a], List[LazyList[a]]) -> Option[(Bosatsu/Lazy::Lazy[a], LazyList[a])]
argument site:
91|      uncons_step(rem.sub(1), get_Lazy(next), pending)
92|    case (rem, [] as e, Mapped(source, fn)):
93|      match uncons_step(rem, source, e):
                                        ^

function site:
91|      uncons_step(rem.sub(1), get_Lazy(next), pending)
92|    case (rem, [] as e, Mapped(source, fn)):
93|      match uncons_step(rem, source, e):
               ^^^^^^^^^^^

where a is an unknown type.
```
which has another two issues:

This seems like it should be accepted since adding a name to pattern that was previously accepted should clearly be accepted. We need a test like this to reproduce it and fix that issue in Infer.

Also, the type display is really bad. We see that we expected `$b$51e` but found `$a$50`. Users have no idea what the heck those things are. To add insult to injury, we say `were a is an unknown type` but `a` is unmentioned anywhere. I know that `$b$51e` is probably an existential type, I think we add the `e` for those. And the `Mapped` introduces an existential type, so what is happening is that `e` has type `List[a]` but we need an empty list of type `List[$b$51e]` because that's the type of source. It took me a lot of thinking here. Had it said `List[a]` found but `List[e] for an existential type e`. Then I might have figured it out. Note, it said the:
```
function type: (Int, LazyList[a], List[LazyList[a]]) -> Option[(Bosatsu/Lazy::Lazy[a], LazyList[a])]
```
not `forall a. (Int, LazyList[a], List[LazyList[a]]) -> Option[(Bosatsu/Lazy::Lazy[a], LazyList[a])]` which is also a bit confusing for me. Does see the type is universal in that context? It seems like it must because we do polymorphic recursion in this loop to handle `Mapped` and `FlatMapped`.

Ideally we would have better error messages when we can't accept the code, but also, due to the argument that `[]` should have been accepted by the recursion checker IMO, we also should have accepted the code.

### PR DESCRIPTION
**Pull request by johnynek**
## Summary
- preserve and use branch-local singleton constructor equality facts during recur lexicographic checking
- treat alias names from singleton patterns as equal to the recur target when validating recursive calls
- widen named singleton-pattern bindings during type inference when the constructor carries no type evidence
- add regression tests for `[]`/`[] as e` and custom `EList`/`EList as e` tuple-recur cases

## Testing
- `sbt "coreJVM/testOnly dev.bosatsu.TypedExprRecursionCheckTest"`
- `./scripts/test_basic.sh`

Fixes #2015

### CODE REVIEW

File: core/src/main/scala/dev/bosatsu/TypedExprRecursionCheck.scala [hunk 1]
```diff
@@ -1829,16 +1881,56 @@ object TypedExprRecursionCheck {
...
+          Some(SingletonCtor.EmptyList)
+        case _                                         =>
+          stripExprWrappers(arg) match {
+            case TypedExpr.Global(
+                  _,
+                  cons: Identifier.Constructor,
+                  _,
+                  _
+                ) =>
+              Some(SingletonCtor.NamedConstructor(cons))
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/TypedExprRecursionCheck.scala]: I don't think we can forget which package we are dealing with. Here we are only tracking Constructor, but in the TypedExpr namespace constructors can collide and must be disambiguated by package.

That wouldn't typecheck to mistake the types, but still, it makes the code confusing to read.

Secondly, we should check that `EmptyList` mixed with `[]` is accepted. They are semantically equivalent but this code seems to be treating list separately from the names. I think we need to normalize back to fully qualified names `package + constructor` not this ad-hoc `SingletonCtor`. We should only have `case class SingletonCtor(pack: PackageName, cons: Constructor)` or something.

File: core/src/main/scala/dev/bosatsu/rankn/Infer.scala [hunk 2]
```diff
@@ -2637,6 +2633,137 @@ object Infer {
...
+          case GenPattern.PositionalStruct(_, Nil)    => true
+          case _                                      => false
+        }
+
+      def maybeWidenNamedBindingType(
+          innerPattern: Pattern,
+          expectedType: Type,
+          innerBindings: List[(Bindable, Type)]
+      ): Infer[Type] = {
+        def renameTypeMetas(
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/rankn/Infer.scala]: this should be in `Type` I think. It only seems to depend on `Type` and we can test it if we expose it there.

File: core/src/main/scala/dev/bosatsu/rankn/Infer.scala [hunk 3]
```diff
@@ -2665,20 +2792,17 @@ object Infer {
...
-          def inner(pat: Pattern) =
-            sigma match {
-              case Expected.Check((t, _)) =>
-                val res =
-                  (GenPattern.Annotation(GenPattern.Named(n, pat), t), t)
-                Infer.pure(res)
-            }
-          // We always return an annotation here, which is the only
-          // place we need to be careful
           for {
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/rankn/Infer.scala:2677]: rewrite this as:
```scala
Expected.Check((t0, _)) = sigma
t1 <- maybeWidenNamedBindingType(p0, t1, ts0)
p1 = GenPattern.Annotation(GenPattern.Named(n, p0), t0)
```

**Comment by johnynek** [comment]
Addressed the review feedback in follow-up commit b4dc8e509:

- normalized singleton constructor matching to fully-qualified `(PackageName, Constructor)` in recursion checking
- normalized `[]` to the same singleton constructor key as `EmptyList`, and added a regression test that mixes `[]` and `EmptyList` in one recur
- moved meta/skolem-to-bound renaming logic into `Type.renameMetaAndSkolemsToBounds` and added a `TypeTest` for it
- rewrote `GenPattern.Named` handling in `Infer.typeCheckPattern` to use `Expected.Check((t0, _)) = sigma` and simplified downstream bindings

Validation:
- `sbt "coreJVM/testOnly dev.bosatsu.TypedExprRecursionCheckTest"`
- `sbt "coreJVM/testOnly dev.bosatsu.rankn.RankNInferTest"`
- `sbt "coreJVM/testOnly dev.bosatsu.rankn.TypeTest"`
- `./scripts/test_basic.sh`

**Comment by johnynek** [comment]
Addressed the review feedback in follow-up commit b4dc8e509:

- normalized singleton constructor matching to fully-qualified  in recursion checking
- normalized  to the same singleton constructor key as , and added a regression test that mixes  and  in one recur
- moved meta/skolem-to-bound renaming logic into  and added a  for it
- rewrote  handling in  to use  and simplified downstream bindings

Validation:
- [info] welcome to sbt 1.12.5 (Oracle Corporation Java 21.0.2)
[info] loading settings for project bosatsu2-build-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project/project
[info] loading settings for project bosatsu2-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project
[success] Generated .bloop/bosatsu2-build-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:52:22 AM
[info] loading settings for project bosatsu2-build from metals.sbt, plugins.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project
[success] Generated .bloop/bosatsu2-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:52:24 AM
[info] loading settings for project bosatsu2 from build.sbt...
[info] resolving key references (18119 settings) ...
[info] set current project to bosatsu2 (in build file:/Users/oscar/code/bosatsu2/)
[warn] there are 3 keys that are not used by any other settings/tasks:
[warn]  
[warn] * cli / nativeImageJvm
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:296
[warn] * cli / nativeImageVersion
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:297
[warn] * docs / Compile / paradoxNavigationDepth
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:80
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] compiling 1 Scala source to /Users/oscar/code/bosatsu2/base/.jvm/target/scala-3.8.2/classes ...
[info] done compiling
Test run dev.bosatsu.TypedExprRecursionCheckTest started
dev.bosatsu.TypedExprRecursionCheckTest: finished 16.231s
Test run dev.bosatsu.TypedExprRecursionCheckTest finished: 0 failed, 0 ignored, 58 total 16.244s
[info] Passed: Total 58, Failed 0, Errors 0, Passed 58
[success] Total time: 21 s, completed Mar 5, 2026, 11:52:47 AM
- [info] welcome to sbt 1.12.5 (Oracle Corporation Java 21.0.2)
[info] loading settings for project bosatsu2-build-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project/project
[info] loading settings for project bosatsu2-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project
[success] Generated .bloop/bosatsu2-build-build.json
[success] Total time: 2 s, completed Mar 5, 2026, 11:52:53 AM
[info] loading settings for project bosatsu2-build from metals.sbt, plugins.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project
[success] Generated .bloop/bosatsu2-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:52:55 AM
[info] loading settings for project bosatsu2 from build.sbt...
[info] resolving key references (18119 settings) ...
[info] set current project to bosatsu2 (in build file:/Users/oscar/code/bosatsu2/)
[warn] there are 3 keys that are not used by any other settings/tasks:
[warn]  
[warn] * cli / nativeImageJvm
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:296
[warn] * cli / nativeImageVersion
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:297
[warn] * docs / Compile / paradoxNavigationDepth
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:80
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
Test run dev.bosatsu.rankn.RankNInferTest started
dev.bosatsu.rankn.RankNInferTest: finished 2.343s
Test run dev.bosatsu.rankn.RankNInferTest finished: 0 failed, 0 ignored, 73 total 2.356s
[info] Passed: Total 73, Failed 0, Errors 0, Passed 73
[success] Total time: 4 s, completed Mar 5, 2026, 11:53:01 AM
- [info] welcome to sbt 1.12.5 (Oracle Corporation Java 21.0.2)
[info] loading settings for project bosatsu2-build-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project/project
[info] loading settings for project bosatsu2-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project
[success] Generated .bloop/bosatsu2-build-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:53:05 AM
[info] loading settings for project bosatsu2-build from metals.sbt, plugins.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project
[success] Generated .bloop/bosatsu2-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:53:06 AM
[info] loading settings for project bosatsu2 from build.sbt...
[info] resolving key references (18119 settings) ...
[info] set current project to bosatsu2 (in build file:/Users/oscar/code/bosatsu2/)
[warn] there are 3 keys that are not used by any other settings/tasks:
[warn]  
[warn] * cli / nativeImageJvm
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:296
[warn] * cli / nativeImageVersion
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:297
[warn] * docs / Compile / paradoxNavigationDepth
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:80
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
Test run dev.bosatsu.rankn.TypeTest started
dev.bosatsu.rankn.TypeTest: finished 8.158s
Test run dev.bosatsu.rankn.TypeTest finished: 0 failed, 0 ignored, 90 total 8.169s
[info] Passed: Total 90, Failed 0, Errors 0, Passed 90
[success] Total time: 9 s, completed Mar 5, 2026, 11:53:17 AM
- [info] welcome to sbt 1.12.5 (Oracle Corporation Java 21.0.2)
[info] loading settings for project bosatsu2-build-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project/project
[info] loading settings for project bosatsu2-build-build from metals.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project/project
[success] Generated .bloop/bosatsu2-build-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:53:22 AM
[info] loading settings for project bosatsu2-build from metals.sbt, plugins.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu2/project
[success] Generated .bloop/bosatsu2-build.json
[success] Total time: 1 s, completed Mar 5, 2026, 11:53:23 AM
[info] loading settings for project bosatsu2 from build.sbt...
[info] resolving key references (18119 settings) ...
[info] set current project to bosatsu2 (in build file:/Users/oscar/code/bosatsu2/)
[warn] there are 3 keys that are not used by any other settings/tasks:
[warn]  
[warn] * cli / nativeImageJvm
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:296
[warn] * cli / nativeImageVersion
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:297
[warn] * docs / Compile / paradoxNavigationDepth
[warn]   +- /Users/oscar/code/bosatsu2/build.sbt:80
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
fib(20) = 10946

[info] Passed: Total 62, Failed 0, Errors 0, Passed 62
[success] Total time: 69 s (0:01:09.0), completed Mar 5, 2026, 11:54:35 AM
[info] Passed: Total 1619, Failed 0, Errors 0, Passed 1619, Ignored 2
[success] Total time: 145 s (0:02:25.0), completed Mar 5, 2026, 11:57:00 AM
