### PR TITLE
Fix bug in python if/else chains

### LINKED ISSUE #1181: python code generation has a bug
see the diff here:

https://github.com/johnynek/bosatsu/pull/1176/commits/d32020f178de4e87fec06256c213aa4d6546d82f

this shouldn't change anything: the order we match cases may change efficiency, but it shouldn't change the result in cases like this.

But inspecting the generated python code it is definitely wrong. The bug seems to be with python generation and not the Matchless AST since that is used for the interpretter tests which pass in both cases.

The cmp_BinNat expression is simple enough, but clearly miscompiled when the order isn't starting with Zero.

### PR DESCRIPTION
**Pull request by johnynek**
close #1181 

This bug has been lurking in python code generation for some time, but only with generative testing did we push hard enough to find it.

### CODE REVIEW

File: core/src/main/scala/org/bykn/bosatsu/Matchless.scala [hunk 1]
```diff
@@ -173,7 +173,20 @@ object Matchless {
...
     }
 
-  case class If(cond: BoolExpr, thenExpr: Expr, elseExpr: Expr) extends Expr
+  case class If(cond: BoolExpr, thenExpr: Expr, elseExpr: Expr) extends Expr {
+    def flatten: (NonEmptyList[(BoolExpr, Expr)], Expr) = {
+      def combine(expr: Expr): (List[(BoolExpr, Expr)], Expr) =
+        expr match {
+          case If(c1, t1, e1) =>
+            val (ifs, e2) = combine(e1)
+            (((c1, t1)) :: ifs, e2)
```
Comment (johnynek) [inline core/src/main/scala/org/bykn/bosatsu/Matchless.scala:182]: previously this code was in PythonGen, but it really only depends on Matchless.Expr. The order was being reversed by appending to the tail: `ifs :+ ((c1, t1))` which for some branches changes semantics (where Matchless has leveraged prior information to do less work).

File: core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala [hunk 2]
```diff
@@ -1878,17 +1878,8 @@ object PythonGen {
             // there is no need to
             loop(in, slotName)
           case Literal(lit) => Env.pure(Code.litToExpr(lit))
-          case If(cond, thenExpr, elseExpr) =>
-            def combine(expr: Expr): (List[(BoolExpr, Expr)], Expr) =
-              expr match {
-                case If(c1, t1, e1) =>
-                  val (ifs, e2) = combine(e1)
-                  (ifs :+ ((c1, t1)), e2)
```
Comment (johnynek) [inline core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala:1886]: note the order is wrong here: we are pushing `c1, t1` on to the end of `ifs` but that came from expanding `e1` so it should come before `e1` since it was before originally.

File: core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala [hunk 3]
```diff
@@ -151,4 +156,21 @@ class MatchlessTest extends AnyFunSuite {
       assert(matchlessRes == matchRes)
     }
   }
+
+  test("If.flatten can be unflattened") {
```
Comment (johnynek) [inline core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala:160]: this test didn't always find the bug (since randomly finding a case is somewhat rare, but after 3 runs, one found it, so I think it would be flakey enough that we would discover the issue).

File: test_workspace/BinNat.bosatsu [hunk 4]
```diff
@@ -71,6 +67,10 @@ def cmp_BinNat(a: BinNat, b: BinNat) -> Comparison:
             case GT | EQ: GT
             case LT: LT
         case Zero: GT
+    case Zero:
```
Comment (johnynek) [inline test_workspace/BinNat.bosatsu:70]: this is more efficient since Zero is rare, but triggered the bug before this fix.
