### PR TITLE
Fix match/recur pattern type errors to point at branch patterns (issue #2013)

### LINKED ISSUE #2013: Bad error message on match type error
I had this code:
```
def uncons_step(rem: Int, current: LazyList[a], pending: List[LazyList[a]]) -> Option[(Lazy[a], LazyList[a])]:
  recur (rem, current):
    case (_, Cons(head, tail)):
      Some((head, append_pending(tail, pending)))
    case _ if cmp_Int(rem, 0) matches LT | EQ:
      None
    case (_, Empty):
      match pending:
        case []:
          None
        case [next, *rest]:
          uncons_step(rem.sub(1), next, rest)
    case (_, Concat(first, second)):
      uncons_step(rem, first, [second, *pending])
    case (_, Suspend(next)):
      uncons_step(rem.sub(1), get_Lazy(next), pending)
    case (_, Mapped(source, fn)):
      match uncons_step(rem, source, []):
        case None:
          uncons_step(rem.sub(1), Empty, pending)
        case Some((head, tail)):
          mapped_head = lazy(() -> fn(get_Lazy(head)))
          mapped_tail = map(tail, fn)
          Some((mapped_head, append_pending(mapped_tail, pending)))
    case (_, FlatMapped(source, fn)):
      match uncons_step(rem.sub(1), source, []):
        case None:
          uncons_step(rem.sub(1), Empty, pending)
        case Some((head, tail)):
          mapped = fn(get_Lazy(head)) 
          uncons_step(rem.sub(1), mapped, [flat_map(tail, fn), *pending])
```

which compiled, if I change the recur to have an extra item in the tuple:
```
def uncons_step(rem: Int, current: LazyList[a], pending: List[LazyList[a]]) -> Option[(Lazy[a], LazyList[a])]:
  recur (rem, pending, current):
    case (_, Cons(head, tail)):
      Some((head, append_pending(tail, pending)))
    case _ if cmp_Int(rem, 0) matches LT | EQ:
      None
    case (_, Empty):
      match pending:
        case []:
          None
        case [next, *rest]:
          uncons_step(rem.sub(1), next, rest)
    case (_, Concat(first, second)):
      uncons_step(rem, first, [second, *pending])
    case (_, Suspend(next)):
      uncons_step(rem.sub(1), get_Lazy(next), pending)
    case (_, Mapped(source, fn)):
      match uncons_step(rem, source, []):
        case None:
          uncons_step(rem.sub(1), Empty, pending)
        case Some((head, tail)):
          mapped_head = lazy(() -> fn(get_Lazy(head)))
          mapped_tail = map(tail, fn)
          Some((mapped_head, append_pending(mapped_tail, pending)))
    case (_, FlatMapped(source, fn)):
      match uncons_step(rem.sub(1), source, []):
        case None:
          uncons_step(rem.sub(1), Empty, pending)
        case Some((head, tail)):
          mapped = fn(get_Lazy(head)) 
          uncons_step(rem.sub(1), mapped, [flat_map(tail, fn), *pending])

```
it gives the error:
```
in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:79:9, package Zafu/Collection/LazyList
type error: expected type Tuple3[Int]
77|
78|def uncons_step(rem: Int, current: LazyList[a], pending: List[LazyList[a]]) -> Option[(Lazy[a], LazyList[a])]:
79|  recur (rem, pending, current):
           ^^^^^^^^^^^^^^^^^^^^^^^

but found type Tuple2
evidence sites:
77|
78|def uncons_step(rem: Int, current: LazyList[a], pending: List[LazyList[a]]) -> Option[(Lazy[a], LazyList[a])]:
79|  recur (rem, pending, current):
           ^^^^^^^^^^^^^^^^^^^^^^^


79|  recur (rem, pending, current):
80|    case (_, Cons(head, tail)):
81|      Some((head, append_pending(tail, pending)))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


83|      None
84|    case (_, Empty):
85|      match pending:
         ^

to:
85|      match pending:
86|        case []:
87|          None
88|        case [next, *rest]:
89|          uncons_step(rem.sub(1), next, rest)
                                               ^


89|          uncons_step(rem.sub(1), next, rest)
90|    case (_, Concat(first, second)):
91|      uncons_step(rem, first, [second, *pending])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


91|      uncons_step(rem, first, [second, *pending])
92|    case (_, Suspend(next)):
93|      uncons_step(rem.sub(1), get_Lazy(next), pending)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


93|      uncons_step(rem.sub(1), get_Lazy(next), pending)
94|    case (_, Mapped(source, fn)):
95|      match uncons_step(rem, source, []):
         ^

to:
 95|      match uncons_step(rem, source, []):
 96|        case None:
 97|          uncons_step(rem.sub(1), Empty, pending)
 98|        case Some((head, tail)):
 99|          mapped_head = lazy(() -> fn(get_Lazy(head)))
100|          mapped_tail = map(tail, fn)
101|          Some((mapped_head, append_pending(mapped_tail, pending)))
                                                                      ^


101|          Some((mapped_head, append_pending(mapped_tail, pending)))
102|    case (_, FlatMapped(source, fn)):
103|      match uncons_step(rem.sub(1), source, []):
          ^

to:
103|      match uncons_step(rem.sub(1), source, []):
104|        case None:
105|          uncons_step(rem.sub(1), Empty, pending)
106|        case Some((head, tail)):
107|          mapped = fn(get_Lazy(head))
108|          uncons_step(rem.sub(1), mapped, [flat_map(tail, fn), *pending])
                                                                            ^
```

The problem is we aren't currently capturing the region of the pattern in the match.

We need to point to the pattern here. One solution could be in the Declaration add `patternRegion: Region` to the `MatchBranch. Then make sure to address it with `replaceRegions`.

If we took this code:
```
    val bp = Indy { indent =>
      val casePat: P[Pattern.Parsed] =
        (P.string("case") *> Parser.spaces).with1 *> Pattern.matchParser
      val guard: P0[Option[NonBinding]] =
        (((Parser.spaces *> Parser.keySpace("if")).backtrack *> arg(indent))).?

      casePat ~ guard
    }
```
And put `Pattern.matchParser.region`  or something, we could keep the region for the Pattern. Then, if we have the Declaration still (which we should when we are typechecking) we can get the region out by inspecting the associated MatchBranch potentially.

A second approach would be to compute the pattern region by exclusion: we know the full match statement region, we know the previous branch region (if any) and we know the current branch expression region. So, by exclusion we can find the region of text that includes the space and the `case: <pattern>` and we could just run a parser on that which skips empty space and the case: and identifies the region within that string of the pattern, and then use that region to compute the original region in the file, which we can use to show the user.

This, second approach may actually be better.

our goal is to put `^^^^^^^^^^^^^` directly under the patterns which have the wrong type, not the branch expressions.

We should make a minimized version of this example and add an error message test to address it.

### PR DESCRIPTION
**Pull request by johnynek**
Implemented a direct fix for issue #2013 by preserving and using match-branch pattern regions end-to-end.
- Added optional `patternRegion` metadata to `Declaration.MatchBranch`, captured from `Pattern.matchParser.region` in `Declaration.matchP`.
- Updated declaration transforms (`replaceRegions` and branch rewrites) to preserve/reset `patternRegion` correctly.
- Added optional `patternRegion` to `Expr.Branch` and preserved it through expression rewrites/traversals.
- In `SourceConverter`, propagated each `Declaration.MatchBranch.patternRegion` into `Expr.Branch` and used it when converting branch patterns.
- In `Infer`, changed match branch pattern checking to use `branch.patternRegion` (fallback to `region(branch.expr)` when unavailable), so tuple-arity/type mismatches in patterns are reported at the pattern site.

Regression coverage:
- Added `ErrorMessageTest` case: `recur pattern tuple mismatch points at the pattern site`, which reproduces the tuple3-vs-tuple2 `recur` branch mismatch and asserts the reported region is the pattern `(_, _)`.
- Updated a few existing `ErrorMessageTest` expected region literals that now correctly report full pattern spans for pattern-originated source-converter errors.

Validation run:
- `sbt -batch "coreJVM/test:compile"` passed.
- `sbt -batch "coreJVM/testOnly dev.bosatsu.ErrorMessageTest"` passed.
- Required pre-push command `scripts/test_basic.sh` passed.

Fixes #2013

### CODE REVIEW

File: core/src/main/scala/dev/bosatsu/Expr.scala [hunk 1]
```diff
@@ -195,7 +197,7 @@ object Expr {
       pattern: Pattern[(PackageName, Constructor), Type],
       guard: Option[Expr[T]],
       expr: Expr[T]
-  )
+  )(using val patternRegion: Option[Region] = None)
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/Expr.scala]: don't make this optional. Let's make it `using val patternRegion: Region` and no default.

File: core/src/main/scala/dev/bosatsu/Declaration.scala [hunk 2]
```diff
@@ -946,7 +949,8 @@ object Declaration {
       pattern: Pattern.Parsed,
       guard: Option[NonBinding],
       body: OptIndent[Declaration]
-  ) derives CanEqual
+  )(using val patternRegion: Option[Region] = None)
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/Declaration.scala]: let's make this required `(using val patternRegion: Region)`

File: core/src/main/scala/dev/bosatsu/Expr.scala [hunk 3]
```diff
@@ -138,7 +138,9 @@ sealed abstract class Expr[T] derives CanEqual {
         Match(
           arg.eraseTags,
           branches.map { b =>
-            Branch(b.pattern, b.guard.map(_.eraseTags), b.expr.eraseTags)
+            Branch(b.pattern, b.guard.map(_.eraseTags), b.expr.eraseTags)(using
+              b.patternRegion
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/Expr.scala]: when erasing the tags, we should also set this to `Region.empty` or whatever that is. The goal here is to forget what regions we have come from when we do this.

File: core/src/main/scala/dev/bosatsu/Expr.scala (hunk 1 above)
Comment (johnynek) [reply core/src/main/scala/dev/bosatsu/Expr.scala]: Updated. `Expr.Branch` now has a required context parameter: `(using val patternRegion: Region)` with no optional/default fallback. I also updated all branch construction sites to pass an explicit region (real pattern region from source when available, `Region.empty` for synthetic/test constructors).

File: core/src/main/scala/dev/bosatsu/Declaration.scala (hunk 2 above)
Comment (johnynek) [reply core/src/main/scala/dev/bosatsu/Declaration.scala]: Done. `Declaration.MatchBranch` is now `(using val patternRegion: Region)` and no longer optional. Parser wiring now captures and supplies this region directly from `Pattern.matchParser.region`, and `replaceRegions`/declaration rewrites preserve or reset it via explicit `using` arguments.

File: core/src/main/scala/dev/bosatsu/Expr.scala (hunk 3 above)
Comment (johnynek) [reply core/src/main/scala/dev/bosatsu/Expr.scala]: Implemented. During `Expr.eraseTags`, branch `patternRegion` is now reset to `Region.empty` so we explicitly forget source-region provenance. I added `Region.empty` in `Region.scala` and use it for erase/synthetic paths.

**Comment by johnynek** [comment]
Addressed all three review comments with concrete code changes. Verified with required pre-push command: `scripts/test_basic.sh` (pass).
