### PR TITLE
Fix #1746: remove Prog reader env and update Java/Python/C backends

### LINKED ISSUE #1746: Simplify: Drop the environment/Reader-monad from Prog
Looking at more Prog-based (IO) code, we very rarely used the Reader part of it (the first type parameter, which is contravariant). Given that simplicity is a main goal, we should remove that. If you need an argument, just pass it. Don't make Prog the everything Monad.

The would change Prog to:

```
external struct Prog[err: +*, res: +*]
```
which is a standard lazy, result-like data type. It represents running an imperative program which can either fail with result of type `err` or succeed with `res`.

We should refactor the code to remove the first type parameter.

The next question is how to deal with CLI args. There are two ways to do this:

1. getArgs: forall e. Prog[e, List[String]]
2. make Main require `List[String] => forall e. Prog[e, Int]`

I favor the second approach. One less built in function, and also getArgs allows any function anywhere to just access the args without any access control. It is poor encapsulation. If they need it, pass it through.

So, we will do the second: struct Main requires a function from List[String].

### PR DESCRIPTION
**Pull request by johnynek**
## Summary
- update `Bosatsu/Prog` to remove reader-environment support (`read_env`, `remap_env`, `with_env`) and make `Prog` take only `[err, res]`
- update `Main` to take argv function form: `List[String] -> forall err. Prog[err, Int]`
- update Java runtime/interpreter (`Predef.scala`) to drop env-threading and invoke main with argv
- update Python runtime (`test_workspace/ProgExt.py`) to derive program from argv and remove env/remap tags
- update C runtime (`c_runtime/bosatsu_ext_Bosatsu_l_Prog.c/.h`) to remove env/remap support and run `main_fn(args)`
- update test workspace and evaluation test fixtures for the new `Prog`/`Main` API
- bump `test_workspace/core_alpha_conf.json` `next_version` to `3.0.0` for this breaking API change

## Testing (local CI-equivalent)
- `sbt "coreJVM/test; cli/test; doc; paradox"`
- `./test_cli.sh`
- `sbt "cli/assembly"`
- python transpile/tests from `ci.yml` (`unittest discover pyout`)
- `sbt "coreJS/test; jsapiJS/compile"`
- `sbt "jsuiJS/test"`
- `sbt "coverage; clean; coreJVM/test; cli/test; coverageReport"`
- `sbt "cli/nativeImage"` + `./bosatsu tool test ...`
- `sbt "cliJSJS/fullOptJS"` + `./bosatsu_node tool test ...`
- `make -C c_runtime install VERSION=$(git rev-parse HEAD)` + `./bosatsu_node lib test ...`
- C runtime/transpile/lib checks from `testC`/`testCMacOS` (including single-assertion output check)
- `sbt "++3.8.1; cli/assembly"` + `scripts/publish_bosatsu_libs.sh` dry run (`libPublishDryRun`)
- `sbt "cli/testOnly dev.bosatsu.GithubWorkflowJsonParityTest"`

Closes #1746.

### CODE REVIEW

File: c_runtime/bosatsu_ext_Bosatsu_l_Prog.c [hunk 1]
```diff
@@ -181,19 +157,6 @@ int bsts_Bosatsu_Prog_run_main(BValue prog, int argc, char **argv)
...
-    case 6:
-    {
-      // RemapEnv(p, f) => (6, p, f)
-      stack = alloc_enum2(3, env, stack);
-      BValue remap_fn = get_enum_index(arg, 1);
-      env = call_fn1(remap_fn, env);
-      arg = get_enum_index(arg, 0);
-      break;
-    }
     case 7:
```
Comment (johnynek) [inline c_runtime/bosatsu_ext_Bosatsu_l_Prog.c]: let's change this tag to `5` so we don't have a gap in the tags.

File: c_runtime/bosatsu_ext_Bosatsu_l_Prog.c [hunk 2]
```diff
@@ -202,6 +165,9 @@ int bsts_Bosatsu_Prog_run_main(BValue prog, int argc, char **argv)
       arg = call_fn1(efn, earg);
       break;
     }
+    default:
+      printf("invalid Prog tag");
```
Comment (johnynek) [inline c_runtime/bosatsu_ext_Bosatsu_l_Prog.c]: should print to stderr and should print the tag. Also, we should be clear: `bosatsu Prog execution fault:` or something.

File: core/src/main/scala/dev/bosatsu/Predef.scala [hunk 3]
```diff
@@ -633,8 +625,6 @@ object PredefImpl {
   private val ProgTagFlatMap = 2
   private val ProgTagRecover = 3
   private val ProgTagApplyFix = 4
-  private val ProgTagReadEnv = 5
-  private val ProgTagRemapEnv = 6
   private val ProgTagEffect = 7
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/Predef.scala]: let's use `5` as the tag here so we keep the order contiguous.

File: test_workspace/Bosatsu/IO/Std.bosatsu [hunk 4]
```diff
@@ -5,27 +5,27 @@ from Bosatsu/IO/Error import IOError
...
+external print_errln_impl: String -> Prog[IOError, Unit]
 
 # read about n bytes from the standard in (may read up to n + 4 bytes to
 # finish a UTF-8 codepoint). n=0 behaves like n=1 (there is no empty read);
 # empty string indicates EOF.
-external def read_stdin_utf8_bytes_impl[env](n: Int) -> Prog[env, IOError, String]
+external read_stdin_utf8_bytes_impl: Int -> Prog[IOError, String]
 
-def println[env](str: String) -> Prog[env, IOError, Unit]:
+def println(str: String) -> Prog[IOError, Unit]:
```
Comment (johnynek) [inline test_workspace/Bosatsu/IO/Std.bosatsu:22]: please add documentation comments above each function.

File: test_workspace/FibBench.bosatsu [hunk 5]
```diff
@@ -30,18 +30,17 @@ def main(args: List[String]):
     case [_, n]: print_fib(n)
     case _: println("expected exactly one arg, got: ${int_to_String(list_len(args, 0))}")
 
-def ignore_err[env, err, res](p: Prog[env, err, res], default: res) -> forall e. Prog[env, e, res]:
+def ignore_err[err, res](p: Prog[err, res], default: res) -> forall e. Prog[e, res]:
```
Comment (johnynek) [inline test_workspace/FibBench.bosatsu]: move to `Prog` package.

File: test_workspace/FibBench.bosatsu [hunk 6]
```diff
@@ -30,18 +30,17 @@ def main(args: List[String]):
...
   p.recover(_ -> pure(default))
 
-def show_error[env](p: Prog[env, IOError, Int]) -> forall e. Prog[env, e, Int]:
+def show_error(p: Prog[IOError, Int]) -> forall e. Prog[e, Int]:
```
Comment (johnynek) [inline test_workspace/FibBench.bosatsu]: move to `IO/Std.bosatsu`

File: test_workspace/FibBench.bosatsu [hunk 7]
```diff
@@ -30,18 +30,17 @@ def main(args: List[String]):
...
   p.recover(ioe -> (
     ioe_str = error_to_String(ioe)
     _ <- ignore_err(println(ioe_str), ()).await()
```
Comment (johnynek) [inline test_workspace/FibBench.bosatsu]: should be `printerr_ln`, not `println`.

File: test_workspace/ProgExt.py [hunk 8]
```diff
@@ -17,8 +16,6 @@ def raise_error(e): return (1, e)
 def flat_map(p, f): return (2, p, f)
 def recover(p, f): return (3, p, f)
 def apply_fix(a, f): return (4, a, f)
-read_env = (5,)
-def remap_env(p, f): return (6, p, f) 
 # this is a thunk we run
 def effect(f): return (7, f)
```
Comment (johnynek) [inline test_workspace/ProgExt.py]: use tag 5 here.

**Comment by johnynek** [comment]
Addressed all review comments in c85dd98e:
- made Prog effect tag contiguous (`5`) across JVM (`Predef.scala`), Python runtime (`ProgExt.py`), and C runtime (`bosatsu_ext_Bosatsu_l_Prog.c` + `bosatsu_ext_Bosatsu_l_IO_l_Std.c`)
- improved C invalid-tag fault message to stderr with tag value
- moved `ignore_err` into `Bosatsu/Prog`
- moved `show_error` into `Bosatsu/IO/Std` and switched to `print_errln`
- added documentation comments above each function in `Bosatsu/IO/Std`

Re-ran requested checks after fixes:
- `testC` (CI-equivalent flow) ✅
- python tests (`transpile` + `unittest`) ✅
- `sbt "cli/test"` ✅

**Comment by johnynek** [comment]
Addressed all review comments in c85dd98e:
- made Prog effect tag contiguous () across JVM (), Python runtime (), and C runtime ( + )
- improved C invalid-tag fault message to stderr with tag value
- moved  into 
- moved  into  and switched to 
- added documentation comments above each function in 

Re-ran requested checks after fixes:
-  (CI-equivalent flow) ✅
- python tests ( + ) ✅
- [info] welcome to sbt 1.12.3 (Oracle Corporation Java 21.0.2)
[info] loading settings for project bosatsu3-build from plugins.sbt...
[info] loading project definition from /Users/oscar/code/bosatsu3/project
[info] loading settings for project bosatsu3 from build.sbt...
[info] resolving key references (17497 settings) ...
[info] set current project to bosatsu3 (in build file:/Users/oscar/code/bosatsu3/)
[warn] there are 3 keys that are not used by any other settings/tasks:
[warn]  
[warn] * cli / nativeImageJvm
[warn]   +- /Users/oscar/code/bosatsu3/build.sbt:278
[warn] * cli / nativeImageVersion
[warn]   +- /Users/oscar/code/bosatsu3/build.sbt:279
[warn] * docs / Compile / paradoxNavigationDepth
[warn]   +- /Users/oscar/code/bosatsu3/build.sbt:80
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] compiling 1 Scala source to /Users/oscar/code/bosatsu3/base/.jvm/target/scala-3.8.1/classes ...
[info] done compiling
dev.bosatsu.JsonJawnTest:
  + Jawn can parse any of the json strings we generate 0.724s
fetched 0 objects.
dev.bosatsu.codegen.clang.ClangGenTest:
  + test_workspace/Ackermann.bosatsu 8.518s
dev.bosatsu.codegen.python.CodeTest:
  + All generated code can be parsed by jython 4.475s
  + test bug with IfElse 0.003s
  + test some Operator examples 0.001s
  + x.eval(Eq, x) == True 0.251s
  + we can do integer comparisons 0.018s
  + x.evalAnd(True) == x 0.255s
  + x.evalAnd(False) == False 0.251s
  + x.evalPlus(y) == (x + y) 0.113s
  + x.evalMinus(y) == (x - y) 0.012s
  + x.evalTimes(y) == (x * y) 0.012s
  + x.eval(op, y).eval(op, z) == op(op(x, y), z 0.038s
  + any sequence of IntOps is optimized 0.356s
  + any sequence of +/- leaves only a single PyInt at the end 0.05s
  + Code.block as at most 1 Pass and if so, only at the end 0.306s
  + simplify is idempotent 0.433s
  + simplify regression: i - (0 - s) keeps stable operand order 0.002s
  + simplify on Ternary removes branches when possible 0.807s
  + identOrParens is true 0.369s
  + (a == b) and (b == c) renders correctly 0.062s
  + comparison operands with not are parenthesized 0.001s
  + simplify applies lambdas 1.135s
  + (lambda x: lambda y: x + y)(y) 0.001s
  + simplify(Map.empty, x) == x 0.449s
  + simplify creates subsets of freeIdents (we can remove ternary branches) 0.802s
dev.bosatsu.ShowEdnInteropTest:
  + edn-java parser accepts showDoc output 13.592s
dev.bosatsu.IOPlatformIOTest:
  + we can roundtrip interfaces through file 9.567s
  + we can roundtrip packages through proto on disk 4.326s
  + relativize handles src and ./src under an absolute root 0.002s
{
  "jobs": {
      "test": {
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "run JVM tests",
                "run":
                  "sbt \"coreJVM/test; cli/test; doc; paradox\"\n./test_cli.sh\n"
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } },
          "timeout-minutes": 30
        },
      "testPY": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "uses": "actions/setup-python@v2",
                "name": "python setup",
                "with": { "python-version": "${{matrix.python}}" }
              }, { "name": "build assembly", "run": "sbt \"cli/assembly\"" },
              {
                "name": "generate python code",
                "run":
                  "./bosatsuj tool transpile --input_dir test_workspace/ --input test_workspace/Bosatsu/IO/Error.bosatsu --input test_workspace/Bosatsu/IO/Std.bosatsu --package_root test_workspace/ python --outdir pyout --externals test_workspace/Prog.bosatsu_externals --evaluators test_workspace/Prog.bosatsu_eval"
              },
              {
                "name": "run python tests",
                "run":
                  "PYTHONPATH=$PYTHONPATH:$(pwd)/test_workspace:$(pwd)/pyout python3 -m unittest discover pyout -v --pattern \"*.py\""
              } ],
          "strategy": { "matrix": { "java": [ "17" ], "python": [ "3.9" ] } },
          "timeout-minutes": 30
        },
      "testJS": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "run coreJS tests",
                "run":
                  "sbt \"coreJS/test; jsapiJS/compile\"\nsbt \"jsuiJS/test\"\n"
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } },
          "timeout-minutes": 30
        },
      "testWithCoverageReport": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "steps": [
              {
                "uses": "actions/checkout@v2.1.0", "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "run tests with coverage",
                "run":
                  "sbt \"coverage; clean; coreJVM/test; cli/test; coverageReport\"\n"
              },
              {
                "uses": "codecov/codecov-action@v5",
                "name": "Upload to Codecov",
                "with": { "token": "${{ secrets.CODECOV_TOKEN }}" }
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } },
          "timeout-minutes": 30
        },
      "buildWithGraal": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "build native image",
                "run":
                  "sbt \"cli/nativeImage\"\ncp cli/target/native-image/bosatsu-cli bosatsu\n"
              },
              {
                "name": "run bosatsu tests",
                "run":
                  "./bosatsu tool test --input_dir test_workspace/ --input test_workspace/Bosatsu/IO/Error.bosatsu --input test_workspace/Bosatsu/IO/Std.bosatsu --package_root test_workspace/\n"
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } }
        },
      "testWithNode": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              { "name": "build node", "run": "sbt \"cliJSJS/fullOptJS\"\n" },
              {
                "name": "run bosatsu tests",
                "run":
                  "./bosatsu_node tool test --input_dir test_workspace/ --input test_workspace/Bosatsu/IO/Error.bosatsu --input test_workspace/Bosatsu/IO/Std.bosatsu --package_root test_workspace/\n"
              },
              {
                "name": "install boehm",
                "run":
                  "sudo apt-get update && sudo apt-get install -y libgc1 libgc-dev"
              },
              {
                "name": "install c runtime",
                "run":
                  "make -C c_runtime install VERSION=$(git rev-parse HEAD)\n"
              },
              {
                "name": "run lib test",
                "run":
                  "./bosatsu_node lib fetch\nmkdir node_out_lib\n./bosatsu_node lib test --outdir node_out_lib\necho \"now test without a given outdir\"\n./bosatsu_node lib test\n"
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } }
        },
      "testC": {
          "needs": "test",
          "runs-on": "ubuntu-latest",
          "strategy": { "matrix": { "java": [ "17" ] } },
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              { "name": "build assembly", "run": "sbt \"cli/assembly\"" },
              {
                "name": "install boehm",
                "run":
                  "sudo apt-get update && sudo apt install -y libgc1 libgc-dev pkg-config"
              },
              {
                "name": "test runtime code",
                "run":
                  "cd c_runtime\nrm -f test_exe\nmake PROFILE=debug && git diff --quiet || { git diff; false; }\nmake boehm_example PROFILE=release\nmake install PROFILE=release CFLAGS=\"-O1 -g\" CPPFLAGS=\"-DBSTS_CI=1\"\n./test_exe && ./boehm_example\nmake bench_exe PROFILE=release\n./bench_exe 1000000 | tee bench_ci.txt\ncd ..\nexport SHA=$(./bosatsuj version -g)\npython3 - <<'PY'\nimport json\nimport os\nimport pathlib\n\nsha = os.environ[\"SHA\"]\nconf_path = pathlib.Path(\".bosatsuc\") / sha / \"cc_conf.json\"\nconf = json.loads(conf_path.read_text())\nassert \"-O1\" in conf[\"flags\"], conf\nassert \"-DBSTS_CI=1\" in conf[\"flags\"] or \"-DBSTS_CI=1\" in conf[\"iflags\"], conf\nprint(f\"validated {conf_path}\")\nPY\n"
              },
              {
                "name": "generate and compile c code",
                "run":
                  "./bosatsuj tool transpile --input_dir test_workspace/ --input test_workspace/Bosatsu/IO/Error.bosatsu --input test_workspace/Bosatsu/IO/Std.bosatsu --package_root test_workspace/ c --outdir c_out --test --exe_out test_exe --cc_flag=-O0 --cc_lib=-lm"
              }, { "name": "run generated c code", "run": "./c_out/test_exe" },
              {
                "name": "check single assertion test output",
                "run":
                  "rm -rf issue1642_repro\nmkdir issue1642_repro\ncat > issue1642_repro/Foo.bosatsu <<'EOF'\npackage Foo\ntest = Assertion(True, \"foo\")\nEOF\n./bosatsuj tool transpile --input issue1642_repro/Foo.bosatsu --package_root issue1642_repro c --outdir issue1642_repro/out --test --exe_out test_exe --cc_flag=-O0 --cc_lib=-lm\nissue1642_repro/out/test_exe | tee issue1642_repro/output.txt\ngrep -Eq '^Foo:$' issue1642_repro/output.txt\ngrep -Eq '^    passed: .*1' issue1642_repro/output.txt\n"
              },
              {
                "name": "run lib test",
                "run":
                  "./bosatsuj lib fetch\nmkdir c_out_lib\n./bosatsuj lib test --outdir c_out_lib --cc_flag=-O0 --cc_lib=-lm\necho \"now test without a given outdir\"\n./bosatsuj lib test --cc_flag=-O0 --cc_lib=-lm\n"
              },
              {
                "name": "run lib build",
                "run":
                  "mkdir c_out_build\n./bosatsuj lib build --outdir c_out_build --main_pack Bosatsu/FibBench --exe_out fib_bench --cc_flag=-O0 --cc_lib=-lm\n./c_out_build/fib_bench 10\n"
              } ],
          "timeout-minutes": 30
        },
      "testCMacOS": {
          "needs": "test",
          "runs-on": "macos-latest",
          "strategy": { "matrix": { "java": [ "17" ] } },
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              { "name": "build assembly", "run": "sbt \"cli/assembly\"" },
              {
                "name": "install boehm", "run": "brew install bdw-gc pkg-config"
              },
              {
                "name": "test runtime code",
                "run":
                  "cd c_runtime\nrm -f test_exe\nmake PROFILE=debug && git diff --quiet || { git diff; false; }\nmake boehm_example PROFILE=release\nmake install PROFILE=release CFLAGS=\"-O1 -g\" CPPFLAGS=\"-DBSTS_CI=1\"\n./test_exe && ./boehm_example\nmake bench_exe PROFILE=release\n./bench_exe 1000000 | tee bench_ci.txt\ncd ..\nexport SHA=$(./bosatsuj version -g)\npython3 - <<'PY'\nimport json\nimport os\nimport pathlib\n\nsha = os.environ[\"SHA\"]\nconf_path = pathlib.Path(\".bosatsuc\") / sha / \"cc_conf.json\"\nconf = json.loads(conf_path.read_text())\nassert \"-O1\" in conf[\"flags\"], conf\nassert \"-DBSTS_CI=1\" in conf[\"flags\"] or \"-DBSTS_CI=1\" in conf[\"iflags\"], conf\nprint(f\"validated {conf_path}\")\nPY\n"
              },
              {
                "name": "generate and compile c code",
                "run":
                  "./bosatsuj tool transpile --input_dir test_workspace/ --input test_workspace/Bosatsu/IO/Error.bosatsu --input test_workspace/Bosatsu/IO/Std.bosatsu --package_root test_workspace/ c --outdir c_out --test --exe_out test_exe --cc_flag=-O0 --cc_lib=-lm"
              }, { "name": "run generated c code", "run": "./c_out/test_exe" },
              {
                "name": "run lib test",
                "run":
                  "./bosatsuj lib fetch\nmkdir c_out_lib\n./bosatsuj lib test --outdir c_out_lib --cc_flag=-O0 --cc_lib=-lm\necho \"now test without a given outdir\"\n./bosatsuj lib test --cc_flag=-O0 --cc_lib=-lm\n"
              },
              {
                "name": "run lib build",
                "run":
                  "mkdir c_out_build\n./bosatsuj lib build --outdir c_out_build --main_pack Bosatsu/FibBench --exe_out fib_bench --cc_flag=-O0 --cc_lib=-lm\n./c_out_build/fib_bench 10\n"
              } ],
          "timeout-minutes": 30
        },
      "libPublishDryRun": {
          "needs": "testC",
          "runs-on": "ubuntu-latest",
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "build assembly", "run": "sbt \"++3.8.1; cli/assembly\""
              },
              {
                "name": "dry run bosatsu lib publish",
                "run":
                  "chmod +x scripts/publish_bosatsu_libs.sh\nscripts/publish_bosatsu_libs.sh\n",
                "env": {
                    "REPO_ROOT": "${{ github.workspace }}",
                    "OUTDIR": "${{ runner.temp }}/bosatsu_lib_publish",
                    "GIT_SHA": "${{ github.sha }}",
                    "URI_BASE": "https://example.invalid/"
                  }
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } }
        }
    },
  "name": "ci",
  "on": { "pull_request": {} }
}
{
  "name": "Codecov on main",
  "on": { "push": { "branches": [ "main" ] } },
  "jobs": {
      "testWithCoverageReport": {
          "runs-on": "ubuntu-latest",
          "steps": [
              {
                "uses": "actions/checkout@v2.1.0", "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java ${{matrix.java}} setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "${{matrix.java}}"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "run tests with coverage",
                "run":
                  "sbt \"coverage; clean; coreJVM/test; cli/test; coverageReport\"\n"
              },
              {
                "uses": "codecov/codecov-action@v5",
                "name": "Upload to Codecov",
                "with": {
                    "token": "${{ secrets.CODECOV_TOKEN }}",
                    "override_branch": "main"
                  }
              } ],
          "strategy": { "matrix": { "java": [ "17" ] } },
          "timeout-minutes": 30
        }
    }
}
dev.bosatsu.codegen.python.PythonGenTest:
  + we can compile Nat.bosatsu 8.1s
  + to_Nat works like identity 0.13s
  + mult works like multiplication 2.889s
  + float literal parsing matches python on hard cases 0.184s
  + bosatsu parser accepts .NaN literal 0.017s
  + we can compile StrConcatExample 1.238s
  + test some list pattern matches 0.978s
  + test euler6 1.163s
  + test PredefTests 3.092s
{
  "name": "Build and Deploy to GitHub Pages",
  "permissions": { "contents": "write" },
  "on": { "push": { "branches": [ "main" ] } },
  "jobs": {
      "build-and-deploy": {
          "runs-on": "ubuntu-latest",
          "env": {
              "BOSATSU_CI": "true",
              "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
            },
          "steps": [ { "uses": "actions/checkout@v2.1.0" },
              { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "java 17 setup",
                "with": { "distribution": "temurin", "java-version": "17" }
              }, { "uses": "sbt/setup-sbt@v1", "name": "install sbt" },
              {
                "name": "build app",
                "run":
                  "export NODE_OPTIONS=--openssl-legacy-provider\nsbt \"jsuiJS/fullOptJS::webpack; docs/paradox\"\nmkdir web_deploy\nmkdir web_deploy/compiler\ncp -a docs/target/paradox/site/main/* web_deploy\ncp jsui/index.html web_deploy/compiler/\ncp jsui/app.css web_deploy/compiler/\ncp jsui/.js/target/scala-3.8.1/scalajs-bundler/main/compiler-jsui-opt-bundle.js web_deploy/compiler/bosatsu_ui.js\n"
              },
              {
                "uses": "peaceiris/actions-gh-pages@v3",
                "name": "Deploy",
                "with": {
                    "github_token": "${{ secrets.GITHUB_TOKEN }}",
                    "publish_dir": "./web_deploy"
                  }
              } ]
        }
    }
}
{
  "name": "Release",
  "on": { "push": { "tags": [ "v*" ] } },
  "permissions": { "contents": "write", "pull-requests": "write" },
  "jobs": {
      "verify_tag": {
          "runs-on": "ubuntu-latest",
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "Java 17 setup",
                "with": { "distribution": "temurin", "java-version": "17" }
              }, { "uses": "sbt/setup-sbt@v1", "name": "Install sbt" },
              {
                "name": "Install b3sum",
                "run": "sudo apt-get update && sudo apt-get install -y b3sum"
              },
              {
                "name": "Verify tag matches sbt version",
                "run":
                  "set -euo pipefail\npython3 scripts/verify_release_tag.py\n",
                "env": { "TAG_NAME": "${{ github.ref_name }}" }
              } ]
        },
      "prepare": {
          "runs-on": "ubuntu-latest",
          "needs": "verify_tag",
          "outputs": {
              "c_runtime_hash": "${{ steps.cruntime.outputs.c_runtime_hash }}",
              "c_runtime_archive":
                "${{ steps.cruntime.outputs.c_runtime_archive }}",
              "git_sha": "${{ steps.cruntime.outputs.git_sha }}"
            },
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              },
              {
                "name": "Install b3sum",
                "run": "sudo apt-get update && sudo apt-get install -y b3sum"
              },
              {
                "name": "Create c_runtime archive",
                "run":
                  "set -euo pipefail\nsha=\"$(git rev-parse HEAD)\"\narchive=\"bosatsu-c-runtime-${sha}.tar.gz\"\ntar -czf \"${archive}\" c_runtime\nhash=\"$(b3sum \"${archive}\" | awk '{print $1}')\"\necho \"git_sha=${sha}\" >> \"$GITHUB_OUTPUT\"\necho \"c_runtime_archive=${archive}\" >> \"$GITHUB_OUTPUT\"\necho \"c_runtime_hash=blake3:${hash}\" >> \"$GITHUB_OUTPUT\"\n",
                "id": "cruntime"
              },
              {
                "uses": "actions/upload-artifact@v4",
                "name": "Upload c_runtime archive",
                "with": {
                    "name": "bosatsu-c-runtime",
                    "path": "${{ steps.cruntime.outputs.c_runtime_archive }}"
                  }
              } ]
        },
      "build_cli": {
          "runs-on": "ubuntu-latest",
          "needs": "prepare",
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "Java 17 setup",
                "with": { "distribution": "temurin", "java-version": "17" }
              }, { "uses": "sbt/setup-sbt@v1", "name": "Install sbt" },
              {
                "name": "Build jar and node JS",
                "run":
                  "sbt \"++3.8.1; cli/assembly; cliJSJS/fullOptJS\"\ncp cli/target/scala-3.8.1/bosatsu-cli-assembly-*.jar bosatsu.jar\ntarget_dir=\"\"\nfor d in cliJS/.js/target/scala-*; do\n  if [ -d \"$d\" ]; then\n    target_dir=\"$d\"\n    break\n  fi\ndone\nif [ -z \"$target_dir\" ]; then\n  echo \"Missing cliJS Scala.js target (run sbt \\\"cliJSJS/fullOptJS\\\")\" >&2\n  exit 1\nfi\nfor candidate in \\\n  \"$target_dir/compiler-clijs-opt.js\" \\\n  \"$target_dir/compiler-clijs-opt/main.js\"\ndo\n  if [ -f \"$candidate\" ]; then\n    cp \"$candidate\" bosatsu_node.js\n    exit 0\n  fi\ndone\necho \"Compiled cliJS output not found in ${target_dir}\" >&2\nexit 1\n",
                "env": {
                    "BOSATSU_C_RUNTIME_HASH":
                      "${{ needs.prepare.outputs.c_runtime_hash }}"
                  }
              },
              {
                "uses": "actions/upload-artifact@v4",
                "name": "Upload jar",
                "with": { "name": "bosatsu-jar", "path": "bosatsu.jar" }
              },
              {
                "uses": "actions/upload-artifact@v4",
                "name": "Upload node JS",
                "with": { "name": "bosatsu-node", "path": "bosatsu_node.js" }
              } ]
        },
      "native_linux": {
          "runs-on": "ubuntu-latest",
          "needs": "prepare",
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "Java 17 setup",
                "with": { "distribution": "temurin", "java-version": "17" }
              }, { "uses": "sbt/setup-sbt@v1", "name": "Install sbt" },
              {
                "name": "Install musl toolchain",
                "run":
                  "sudo apt-get update && sudo apt-get install -y musl-tools build-essential"
              },
              {
                "name": "Build musl zlib",
                "run":
                  "set -euo pipefail\nzlib_version=\"1.3.1\"\nzlib_sha256=\"9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23\"\nzlib_url=\"https://github.com/madler/zlib/releases/download/v${zlib_version}/zlib-${zlib_version}.tar.gz\"\ncurl -fsSL \"$zlib_url\" -o /tmp/zlib.tar.gz\necho \"${zlib_sha256}  /tmp/zlib.tar.gz\" | sha256sum -c -\nrm -rf /tmp/zlib-src\nmkdir -p /tmp/zlib-src\ntar -xzf /tmp/zlib.tar.gz -C /tmp/zlib-src --strip-components=1\ncd /tmp/zlib-src\nCC=musl-gcc ./configure --static --prefix=/usr/local/musl\nmake -j\"$(nproc)\"\nsudo make install\n"
              },
              {
                "name": "Build native image (linux static)",
                "run":
                  "sbt \"++3.8.1; cli/nativeImage\"\ncp cli/target/native-image/bosatsu-cli bosatsu-linux\n",
                "env": {
                    "BOSATSU_C_RUNTIME_HASH":
                      "${{ needs.prepare.outputs.c_runtime_hash }}",
                    "BOSATSU_STATIC_NATIVE_IMAGE": "true",
                    "BOSATSU_NATIVE_IMAGE_LIBC": "musl",
                    "BOSATSU_NATIVE_IMAGE_CLIB_PATH": "/usr/local/musl/lib",
                    "CC": "musl-gcc"
                  }
              },
              {
                "uses": "actions/upload-artifact@v4",
                "name": "Upload linux native image",
                "with": {
                    "name": "bosatsu-native-linux", "path": "bosatsu-linux"
                  }
              } ]
        },
      "native_macos": {
          "runs-on": "macos-14",
          "needs": "prepare",
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/setup-java@v5",
                "name": "Java 17 setup",
                "with": {
                    "distribution": "temurin",
                    "java-version": "17",
                    "architecture": "aarch64"
                  }
              }, { "uses": "sbt/setup-sbt@v1", "name": "Install sbt" },
              {
                "name": "Build native image (macos)",
                "run":
                  "sbt \"++3.8.1; cli/nativeImage\"\ncp cli/target/native-image/bosatsu-cli bosatsu-macos\nuname -m\nfile bosatsu-macos\nfile bosatsu-macos | grep -q \"arm64\" || { echo \"Expected arm64 binary\"; exit 1; }\n",
                "env": {
                    "BOSATSU_C_RUNTIME_HASH":
                      "${{ needs.prepare.outputs.c_runtime_hash }}"
                  }
              },
              {
                "uses": "actions/upload-artifact@v4",
                "name": "Upload macos native image",
                "with": {
                    "name": "bosatsu-native-macos", "path": "bosatsu-macos"
                  }
              } ]
        },
      "release": {
          "runs-on": "ubuntu-latest",
          "needs": [ "prepare", "build_cli", "native_linux", "native_macos" ],
          "steps": [
              {
                "uses": "actions/checkout@v4",
                "name": "Check out code",
                "with": { "fetch-depth": 0 }
              }, { "uses": "coursier/cache-action@v6" },
              {
                "uses": "actions/download-artifact@v4",
                "name": "Download artifacts",
                "with": { "path": "release_assets", "merge-multiple": true }
              },
              {
                "uses": "actions/setup-java@v5",
                "name": "Java 17 setup",
                "with": { "distribution": "temurin", "java-version": "17" }
              }, { "uses": "sbt/setup-sbt@v1", "name": "Install sbt" },
              {
                "name": "Install b3sum",
                "run": "sudo apt-get update && sudo apt-get install -y b3sum"
              },
              {
                "name": "Publish JVM/JS artifacts to Sonatype",
                "run": "sbt ci-release",
                "env": {
                    "BOSATSU_C_RUNTIME_HASH":
                      "${{ needs.prepare.outputs.c_runtime_hash }}",
                    "PGP_PASSPHRASE": "${{ secrets.PGP_PASSPHRASE }}",
                    "PGP_SECRET": "${{ secrets.PGP_SECRET }}",
                    "SONATYPE_PASSWORD": "${{ secrets.SONATYPE_PASSWORD }}",
                    "SONATYPE_USERNAME": "${{ secrets.SONATYPE_USERNAME }}"
                  }
              },
              {
                "name": "Build assembly for lib publish",
                "run": "sbt \"++3.8.1; cli/assembly\"",
                "env": {
                    "BOSATSU_C_RUNTIME_HASH":
                      "${{ needs.prepare.outputs.c_runtime_hash }}"
                  }
              },
              {
                "name": "Publish Bosatsu libraries",
                "run":
                  "chmod +x scripts/publish_bosatsu_libs.sh\nscripts/publish_bosatsu_libs.sh\n",
                "env": {
                    "REPO_ROOT": "${{ github.workspace }}",
                    "OUTDIR": "${{ github.workspace }}/.bosatsu_lib_publish",
                    "GIT_SHA": "${{ needs.prepare.outputs.git_sha }}",
                    "URI_BASE":
                      "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/"
                  }
              },
              {
                "name": "Stage release assets",
                "run":
                  "set -euo pipefail\nmkdir -p release_assets\ncp bosatsu release_assets/\ncp proto/src/main/protobuf/bosatsu/TypedAst.proto release_assets/\ncp .bosatsu_lib_publish/*.bosatsu_lib release_assets/\nchmod +x release_assets/bosatsu || true\nrequired_files=(\n  \"bosatsu.jar\"\n  \"bosatsu_node.js\"\n  \"bosatsu-linux\"\n  \"bosatsu-macos\"\n  \"bosatsu\"\n  \"TypedAst.proto\"\n  \"${C_RUNTIME_ARCHIVE}\"\n)\nfor file in \"${required_files[@]}\"; do\n  if [ ! -f \"release_assets/${file}\" ]; then\n    echo \"Missing release asset: ${file}\" >&2\n    exit 1\n  fi\ndone\n",
                "env": {
                    "C_RUNTIME_ARCHIVE":
                      "${{ needs.prepare.outputs.c_runtime_archive }}"
                  }
              },
              {
                "name": "Create SHA256SUMS",
                "run":
                  "set -euo pipefail\ncd release_assets\nfind . -maxdepth 1 -type f ! -name 'SHA256SUMS' ! -name 'B3SUMS' -print0 \\\n  | sort -z \\\n  | xargs -0 sha256sum > SHA256SUMS\n",
                "env": {
                    "C_RUNTIME_ARCHIVE":
                      "${{ needs.prepare.outputs.c_runtime_archive }}"
                  }
              },
              {
                "name": "Create B3SUMS",
                "run":
                  "set -euo pipefail\ncd release_assets\nfind . -maxdepth 1 -type f ! -name 'B3SUMS' -print0 \\\n  | sort -z \\\n  | xargs -0 b3sum > B3SUMS\n",
                "env": {
                    "C_RUNTIME_ARCHIVE":
                      "${{ needs.prepare.outputs.c_runtime_archive }}"
                  }
              },
              {
                "uses": "softprops/action-gh-release@v2",
                "name": "Create GitHub release",
                "with": {
                    "name": "Release ${{ github.ref_name }}",
                    "tag_name": "${{ github.ref_name }}",
                    "generate_release_notes": true,
                    "files": "release_assets/*\n"
                  },
                "env": { "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}" }
              },
              {
                "name": "Create PR for core_conf.json changes",
                "run":
                  "set -euo pipefail\necho \"Changes after bosatsu lib publish:\"\ngit status\ngit diff\n\ngit config user.name \"bosatsu-release-bot\"\ngit config user.email \"bosatsu-release-bot@users.noreply.github.com\"\n\ngit add **/*_conf.json\n\nif git diff --cached --quiet; then\n  echo \"No core_conf.json changes to commit, skipping push.\"\n  exit 0\nfi\n\nbranch=\"release/conf-${GITHUB_REF_NAME}\"\ngit checkout -B \"$branch\"\ngit commit -m \"Update lib conf.jsons for ${GITHUB_REF_NAME}\"\ngit push -u --force-with-lease origin \"$branch\"\n\nif gh pr view \"$branch\" >/dev/null 2>&1; then\n  echo \"PR already exists for ${branch}, skipping create.\"\n  exit 0\nfi\n\ngh pr create \\\n  --base main \\\n  --head \"$branch\" \\\n  --title \"Update lib conf.jsons for ${GITHUB_REF_NAME}\" \\\n  --body \"Automated updates for ${GITHUB_REF_NAME} release.\"\n",
                "env": {
                    "GITHUB_REF_NAME": "${{ github.ref_name }}",
                    "GH_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                  }
              } ]
        }
    }
}
dev.bosatsu.GithubWorkflowJsonParityTest:
  + lib json write matches .github/workflows/ci.yml 14.345s
  + lib json write matches .github/workflows/codecov_main.yml 3.861s
  + lib json write matches .github/workflows/deploy_web.yml 3.573s
  + lib json write matches .github/workflows/release.yml 2.322s
Bosatsu/Collection/Queue:
  queue tests:
    queue properties:
      pop-law/toList:
        100 tests, [32m100 passed[0m 0 failed
      reverse isomorphism:
        100 tests, [32m100 passed[0m 0 failed
      push is the same as reverse prepend reverse:
        100 tests, [32m100 passed[0m 0 failed
      pop isomorphism:
        100 tests, [32m100 passed[0m 0 failed
      400 tests, [32m400 passed[0m 0 failed
    412 tests, [32m412 passed[0m 0 failed
Bar:
  1 test, [32m1 passed[0m 0 failed
{ "value": true, "message": "got the right string" }
8
[ 8, 15 ]
AvlTree:
  AvlTree tests:
    contains tests:
      6 tests, [32m6 passed[0m 0 failed
    size tests:
      5 tests, [32m5 passed[0m 0 failed
    height_tests:
      30 tests, [32m30 passed[0m 0 failed
    fold_left_tests:
      3 tests, [32m3 passed[0m 0 failed
    fold_right_tests:
      3 tests, [32m3 passed[0m 0 failed
    47 tests, [32m47 passed[0m 0 failed

Bar:
  1 test, [32m1 passed[0m 0 failed

Bo/Test:
  1 test, [32m1 passed[0m 0 failed

Bosatsu/Bool:
  not tests:
    2 tests, [32m2 passed[0m 0 failed

Bosatsu/Char:
  Char tests:
    string_to_Char:
      4 tests, [32m4 passed[0m 0 failed
    len tests:
      4 tests, [32m4 passed[0m 0 failed
    last_String:
      4 tests, [32m4 passed[0m 0 failed
    codepoint tests:
      20 tests, [32m20 passed[0m 0 failed
    radix tests:
      19 tests, [32m19 passed[0m 0 failed
    ascii tests:
      30 tests, [32m30 passed[0m 0 failed
    interop tests:
      8 tests, [32m8 passed[0m 0 failed
    match tests:
      7 tests, [32m7 passed[0m 0 failed
    glob_match_suites:
      9 tests, [32m9 passed[0m 0 failed
    partition tests:
      6 tests, [32m6 passed[0m 0 failed
    111 tests, [32m111 passed[0m 0 failed

Bosatsu/Collection/Queue:
  queue tests:
    queue properties:
      pop-law/toList:
        100 tests, [32m100 passed[0m 0 failed
      reverse isomorphism:
        100 tests, [32m100 passed[0m 0 failed
      push is the same as reverse prepend reverse:
        100 tests, [32m100 passed[0m 0 failed
      pop isomorphism:
        100 tests, [32m100 passed[0m 0 failed
      400 tests, [32m400 passed[0m 0 failed
    412 tests, [32m412 passed[0m 0 failed

Bosatsu/Collection/TreeList:
  TreeList tests:
    9 tests, [32m9 passed[0m 0 failed

Bosatsu/Example/ApplicativeTraverse:
  applicative/traverse tests:
    4 tests, [32m4 passed[0m 0 failed

Bosatsu/List:
  List tests:
    string tests:
      3 tests, [32m3 passed[0m 0 failed
    get/set tests:
      8 tests, [32m8 passed[0m 0 failed
    zip tests:
      3 tests, [32m3 passed[0m 0 failed
    sort tests:
      4 tests, [32m4 passed[0m 0 failed
    50 tests, [32m50 passed[0m 0 failed

Bosatsu/Num/BinNat:
  BinNat tests:
    round trip laws:
      11 tests, [32m11 passed[0m 0 failed
    next law:
      4 tests, [32m4 passed[0m 0 failed
    mul2 law:
      5 tests, [32m5 passed[0m 0 failed
    39 tests, [32m39 passed[0m 0 failed

Bosatsu/Num/Nat:
  Nat tests:
    to_Nat/to_Int tests:
      6 tests, [32m6 passed[0m 0 failed
    21 tests, [32m21 passed[0m 0 failed

Bosatsu/NumberProps:
  properties:
    Int props:
      divmod law:
        100 tests, [32m100 passed[0m 0 failed
    Nat props:
      if is_even(n) then mul2(div2(n)) == n:
        100 tests, [32m100 passed[0m 0 failed
      cmp_Nat matches cmp_Int:
        100 tests, [32m100 passed[0m 0 failed
      add homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      sub_Nat homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      mult homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      exp homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      mul2 == x -> mult(2, x):
        100 tests, [32m100 passed[0m 0 failed
      divmod homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      800 tests, [32m800 passed[0m 0 failed
    BinNat props:
      if is_even(n) then mul2(div2(n)) == n:
        100 tests, [32m100 passed[0m 0 failed
      cmp_BinNat matches cmp_Int:
        100 tests, [32m100 passed[0m 0 failed
      cmp_BinNat matches eq_BinNat:
        100 tests, [32m100 passed[0m 0 failed
      add homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      sub_BinNat homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      sub_BinNat_Option is None implies a < b:
        100 tests, [32m100 passed[0m 0 failed
      mult homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      exp homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      mul2 == x -> mult(2, x):
        100 tests, [32m100 passed[0m 0 failed
      divmod homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      1000 tests, [32m1000 passed[0m 0 failed
    BinInt props:
      add homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      sub homomorphism:
        100 tests, [32m100 passed[0m 0 failed
      x + (-x) == 0:
        100 tests, [32m100 passed[0m 0 failed
      x + |x| == 0 or 2x:
        100 tests, [32m100 passed[0m 0 failed
      x + not(x) == x - x - 1 = -1:
        100 tests, [32m100 passed[0m 0 failed
      500 tests, [32m500 passed[0m 0 failed
    2400 tests, [32m2400 passed[0m 0 failed

Bosatsu/Testing/Properties:
  integer props:
    not_law:
      100 tests, [32m100 passed[0m 0 failed
    shift_unshift_law:
      100 tests, [32m100 passed[0m 0 failed
    x & y is >= 0 implies x >= 0 or y >= 0:
      100 tests, [32m100 passed[0m 0 failed
    300 tests, [32m300 passed[0m 0 failed

Euler/Four:
  1 test, [32m1 passed[0m 0 failed

Euler/One:
  1 test, [32m1 passed[0m 0 failed

Euler/P5:
  1 test, [32m1 passed[0m 0 failed

Euler/P6:
  two examples:
    2 tests, [32m2 passed[0m 0 failed

Euler/P7:
  euler 7:
    3 tests, [32m3 passed[0m 0 failed

Euler/Three:
  1 test, [32m1 passed[0m 0 failed

Euler/Two:
  1 test, [32m1 passed[0m 0 failed

IntTest:
  integer tests:
    addition and subtraction:
      19 tests, [32m19 passed[0m 0 failed
    string tests:
      2 tests, [32m2 passed[0m 0 failed
    and tests:
      19 tests, [32m19 passed[0m 0 failed
    or tests:
      13 tests, [32m13 passed[0m 0 failed
    xor tests:
      13 tests, [32m13 passed[0m 0 failed
    shift tests:
      7 tests, [32m7 passed[0m 0 failed
    73 tests, [32m73 passed[0m 0 failed

Issue1633:
  Issue1633 tests:
    2 tests, [32m2 passed[0m 0 failed

ListPat:
  ListPat tests:
    8 tests, [32m8 passed[0m 0 failed

Parser:
  Parser tests:
    9 tests, [32m9 passed[0m 0 failed

PatternExamples:
  PatternExamples:
    3 tests, [32m3 passed[0m 0 failed

PredefTests:
  Predef tests:
    Int tests:
      51 tests, [32m51 passed[0m 0 failed
    String tests:
      31 tests, [32m31 passed[0m 0 failed
    Float tests:
      53 tests, [32m53 passed[0m 0 failed
    135 tests, [32m135 passed[0m 0 failed

Quicksort:
  quicksort:
    5 tests, [32m5 passed[0m 0 failed

RecordSet/Library:
  reordering:
    1 test, [32m1 passed[0m 0 failed

StrConcatExample:
  interpolation:
    5 tests, [32m5 passed[0m 0 failed

StringPatternBranchTests:
  String pattern branch tests:
    34 tests, [32m34 passed[0m 0 failed

3682 tests, [32m3682 passed[0m 0 failed
"this is Foo"
dev.bosatsu.PathModuleTest:
  + tool test some hand written examples 0.476s
  + no roots means no Package 0.108s
  + empty path is not okay for a package 0.197s
  + if we add to a path that becomes Package 0.334s
  + if none of the roots are prefixes we have none 0.247s
  + tool test direct run of a file 46.69s
  + tool test search run of a file 0.253s
  + tool test python transpile on the entire test_workspace 0.968s
  + tool test search with json write 0.237s
  + tool test search json apply 0.789s
  + tool test search json traverse 0.704s
  + error coverage on json command 5.976s
  + tool test running all test in test_workspace 65.304s
  + evaluation by name with shadowing 0.119s
[info] Passed: Total 57, Failed 0, Errors 0, Passed 57
[success] Total time: 132 s (0:02:12.0), completed Feb 20, 2026, 8:41:29 AM ✅
