### PR TITLE
Fix Int recursion checker for TreeList-style guarded fallthrough and `operator - = sub` alias lowering

### LINKED ISSUE #1983: int solver can't handle a case it should in TreeList
in test_workspace/TreeList.bosatsu

if I try to rewrite `def get` to:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (_, []): None
            case (idx, [Single(h), *rest]):
                if eq_Int(idx, 0): Some(h)
                else: go(rest, idx - 1)
            case (_, [Branch(s, _, t1, t2), *rest]):
                # we can either skip just one, or skip the entire Tree
                match cmp_Int(idx, s):
                    case LT: go([t1, t2, *rest], idx - 1)
                    case _: go(rest, idx - s)
    go(trees, idx)

```
I get the errors:
```

in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:70:23, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: lower recursive Int argument
recur target: idx
path condition: (and (not (< idx_0 0)) (not (= idx_1 0)) (not (= idx_1 0)))
solver detail: unable to lower recursive argument (ap
    (var
        Bosatsu/Collection/TreeList::operator -
        (Bosatsu/Predef::Int, Bosatsu/Predef::Int) -> Bosatsu/Predef::Int)
    (var idx Bosatsu/Predef::Int) (lit 1 Bosatsu/Predef::Int)
    Bosatsu/Predef::Int) to SMT Int expression; hint: rewrite recursive argument using canonical Int operations, e.g. idx.sub(1) or idx.add(-1)
68|            case (idx, [Single(h), *rest]):
69|                if eq_Int(idx, 0): Some(h)
70|                else: go(rest, idx - 1)
                         ^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:74:30, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: lower recursive Int argument
recur target: idx
path condition: (and (not (< idx_0 0)) (< idx_0 s_1))
solver detail: unable to lower recursive argument (ap
    (var
        Bosatsu/Collection/TreeList::operator -
        (Bosatsu/Predef::Int, Bosatsu/Predef::Int) -> Bosatsu/Predef::Int)
    (var idx Bosatsu/Predef::Int) (lit 1 Bosatsu/Predef::Int)
    Bosatsu/Predef::Int) to SMT Int expression; hint: rewrite recursive argument using canonical Int operations, e.g. idx.sub(1) or idx.add(-1)
72|                # we can either skip just one, or skip the entire Tree
73|                match cmp_Int(idx, s):
74|                    case LT: go([t1, t2, *rest], idx - 1)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:75:29, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: lower recursive Int argument
recur target: idx
path condition: (and (not (< idx_0 0)) (not (< idx_0 s_1)))
solver detail: unable to lower recursive argument (ap
    (var
        Bosatsu/Collection/TreeList::operator -
        (Bosatsu/Predef::Int, Bosatsu/Predef::Int) -> Bosatsu/Predef::Int)
    (var idx Bosatsu/Predef::Int) (var s Bosatsu/Predef::Int)
    Bosatsu/Predef::Int) to SMT Int expression; hint: rewrite recursive argument using canonical Int operations, e.g. idx.sub(1) or idx.add(-1)
73|                match cmp_Int(idx, s):
74|                    case LT: go([t1, t2, *rest], idx - 1)
75|                    case _: go(rest, idx - s)
                               ^^^^^^^^^^^^^^^^^
```

using:
```
oscar@mac bosatsu % ./bosatsu
Missing expected command (lib or tool or version or c-runtime)!

Usage: bosatsu lib tool version c-runtime

a total and functional programming language

version: 0.0.41
scala-version: 3.8.2
git-sha: 2db8da343b19323df62d3844407c41cbf75286ae
```

just above in the file we have: `operator - = sub`
So we should be able to see that `operator -` can be lowered into `sub`. I think this should be handled.

If I replace to using `sub` I get a different set of errors:

```
in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:70:23, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_1 (* (- 1) 1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (not (= idx_1 0)) (not (= idx_1 0)))
model:
((define-fun idx_0 () Int 0) (define-fun idx_1 () Int (- 1)))
68|            case (idx, [Single(h), *rest]):
69|                if eq_Int(idx, 0): Some(h)
70|                else: go(rest, idx.sub(1))
                         ^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:74:30, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) 1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (< idx_0 s_1))
model:
((define-fun s_1 () Int 1) (define-fun idx_0 () Int 0))
72|                # we can either skip just one, or skip the entire Tree
73|                match cmp_Int(idx, s):
74|                    case LT: go([t1, t2, *rest], idx.sub(1))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:75:29, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (< (+ idx_0 (* (- 1) s_1)) idx_0)
recur target: idx
path condition: (and (not (< idx_0 0)) (not (< idx_0 s_1)))
model:
((define-fun s_1 () Int 0) (define-fun idx_0 () Int 0))
73|                match cmp_Int(idx, s):
74|                    case LT: go([t1, t2, *rest], idx.sub(1))
75|                    case _: go(rest, idx.sub(s))
                               ^^^^^^^^^^^^^^^^^^^^
```
The first error seems wrong. We should know that `idx >= 0` after the first branch. Then we have `if eq_Int(idx, 0):` and we pass that so we know `idx >= 0` and `not(idx == 0)`. That should be enough to see that `idx >= 1` so `idx - 1 >= 0` which is an allowed recursion, but we miss it.

The last two are a real error becauase `idx == 0` is still a possibility and it isn't handled. So, yay! it found a bug. I refactor to this:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (_, []): None
            case (0, [Single(h), *_] | [Branch(_, h, _, _), *_]): Some(h)
            case (idx, [Single(_), *rest]): go(rest, idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]):
                # we can either skip just one, or skip the entire Tree
                match cmp_Int(idx, s):
                    case LT: go([t1, t2, *rest], idx.sub(1))
                    case _: go(rest, idx.sub(s))
    go(trees, idx)

```
Which I think should work. Now we are checking if `idx == 0` due to the match, and note that `[Single(h), *_] | [Branch(_, h, _, _), *_]` is a total match for the rest of the pattern. All cases of `idx == 0` have to match that because empty list has already matched in the line above. This code should compile, but it doesn't. It gives:
```
in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:69:45, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_1 (* (- 1) 1)) 0)
recur target: idx
path condition: (not (< idx_0 0))
model:
((define-fun idx_1 () Int 0) (define-fun idx_0 () Int 0))
67|            case (_, []): None
68|            case (0, [Single(h), *_] | [Branch(_, h, _, _), *_]): Some(h)
69|            case (idx, [Single(_), *rest]): go(rest, idx.sub(1))
                                               ^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:73:30, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) 1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (< idx_0 s_1))
model:
((define-fun s_1 () Int 1) (define-fun idx_0 () Int 0))
71|                # we can either skip just one, or skip the entire Tree
72|                match cmp_Int(idx, s):
73|                    case LT: go([t1, t2, *rest], idx.sub(1))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:74:29, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (< (+ idx_0 (* (- 1) s_1)) idx_0)
recur target: idx
path condition: (and (not (< idx_0 0)) (not (< idx_0 s_1)))
model:
((define-fun s_1 () Int 0) (define-fun idx_0 () Int 0))
72|                match cmp_Int(idx, s):
73|                    case LT: go([t1, t2, *rest], idx.sub(1))
74|                    case _: go(rest, idx.sub(s))
                               ^^^^^^^^^^^^^^^^^^^^
```
So, it is not able to see even in the first case that `idx.sub(1) >= 0` despite us showing that `idx >= 0` and `idx != 0`. It should know that. I think may not be able to see match correctly where the scrutinee is an int judgement?

Thinking the match is the problem, I change to:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (0, [Single(h), *_] | [Branch(_, h, _, _), *_]): Some(h)
            case (_, [Single(_), *rest]) if cmp_Int(idx, 1) matches EQ | GT: go(rest, idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]):
                if cmp_Int(idx, s) matches LT:
                    # we can either skip just one, or skip the entire Tree
                    go([t1, t2, *rest], idx.sub(1))
                else:
                    go(rest, idx.sub(s))
            case _: None
    go(trees, idx)

```
but still it fails:
```
in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:72:21, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) 1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (< idx_0 s_1))
model:
((define-fun s_1 () Int 1) (define-fun idx_0 () Int 0))
70|                if cmp_Int(idx, s) matches LT:
71|                    # we can either skip just one, or skip the entire Tree
72|                    go([t1, t2, *rest], idx.sub(1))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:74:21, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (< (+ idx_0 (* (- 1) s_1)) idx_0)
recur target: idx
path condition: (and (not (< idx_0 0)) (not (< idx_0 s_1)))
model:
((define-fun s_1 () Int 0) (define-fun idx_0 () Int 0))
72|                    go([t1, t2, *rest], idx.sub(1))
73|                else:
74|                    go(rest, idx.sub(s))
                       ^^^^^^^^^^^^^^^^^^^^
```
then I write:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (0, [Single(h), *_] | [Branch(_, h, _, _), *_]): Some(h)
            case (_, [Single(_), *rest]) if cmp_Int(idx, 1) matches EQ | GT: go(rest, idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(idx, s) matches LT:
                # we can either skip just one, or skip the entire Tree
                go([t1, t2, *rest], idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(s, 0) matches GT:
                go(rest, idx.sub(s))
            case _: None
    go(trees, idx)

```
But it can't see that `idx != 0` from the second line:
```
in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:71:17, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) 1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (< idx_0 s_1))
model:
((define-fun s_1 () Int 1) (define-fun idx_0 () Int 0))
69|            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(idx, s) matches LT:
70|                # we can either skip just one, or skip the entire Tree
71|                go([t1, t2, *rest], idx.sub(1))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:73:17, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) s_1)) 0)
recur target: idx
path condition: (and (not (< idx_0 0)) (> s_1 0))
model:
((define-fun s_1 () Int 1) (define-fun idx_0 () Int 0))
71|                go([t1, t2, *rest], idx.sub(1))
72|            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(s, 0) matches GT:
73|                go(rest, idx.sub(s))
                   ^^^^^^^^^^^^^^^^^^^^
```
So then I rewrite to:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (_, _) if cmp_Int(idx, 0) matches EQ:
                match trees:
                    case [Single(h), *_] | [Branch(_, h, _, _), *_]: Some(h)
                    case []: None
            case (_, [Single(_), *rest]) if cmp_Int(idx, 1) matches EQ | GT: go(rest, idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(idx, s) matches LT:
                # we can either skip just one, or skip the entire Tree
                go([t1, t2, *rest], idx.sub(1))
            case (_, [Branch(s, _, _, _), *rest]) if cmp_Int(s, 0) matches GT:
                go(rest, idx.sub(s))
            case _: None
    go(trees, idx)
```
But it tells me:
```
in file: /Users/oscar/code/bosatsu/test_workspace/TreeList.bosatsu:76:17, package Bosatsu/Collection/TreeList
cannot prove Int recursion obligation for go: (>= (+ idx_0 (* (- 1) s_1)) 0)
recur target: idx
path condition: (and (and (not (< idx_0 0)) (not (= idx_0 0))) (> s_1 0))
model:
((define-fun s_1 () Int 2) (define-fun idx_0 () Int 1))
74|                go([t1, t2, *rest], idx.sub(1))
75|            case (_, [Branch(s, _, _, _), *rest]) if cmp_Int(s, 0) matches GT:
76|                go(rest, idx.sub(s))
                   ^^^^^^^^^^^^^^^^^^^^
```
so here it can't see the the two `Branch` cases are sharing information. We should see that the first pattern is a superset of the second Branch: since `Branch(s, _, t1, t2), *rest]` matches everything that `[Branch(s, _, _, _), *rest]` does (and TotalityCheck can tell us that), then we know that the previous guard gives us information here, we know that `not(cmp_Int(idx, s) matches LT)` so, `s <= idx`, but that is not showing up in the path condition, so it can't see that `idx - s` is still `>=0`

So I finally rewrite to:
```
def get(TreeList(trees): TreeList[a], idx: Int) -> Option[a]:
    def go(trees, idx):
        loop (idx, trees):
            case _ if cmp_Int(idx, 0) matches LT: None
            case (_, _) if cmp_Int(idx, 0) matches EQ:
                match trees:
                    case [Single(h), *_] | [Branch(_, h, _, _), *_]: Some(h)
                    case []: None
            case (_, [Single(_), *rest]) if cmp_Int(idx, 1) matches EQ | GT: go(rest, idx.sub(1))
            case (_, [Branch(s, _, t1, t2), *rest]) if cmp_Int(idx, s) matches LT:
                # we can either skip just one, or skip the entire Tree
                go([t1, t2, *rest], idx.sub(1))
            case (_, [Branch(s, _, _, _), *rest]):
                if cmp_Int(s, 0) matches GT:
                    if cmp_Int(idx, s) matches GT | EQ:
                        # this always happens but the int checker can't see it yet as of this writing
                        go(rest, idx.sub(s))
                    else: None
                else: None
            case _: None
    go(trees, idx)
```

and it is accepted, but it is clearly doing a wasted comparison to satisfy the typechecker.

We should add some tests around this problem. I think the key problem is that it can't see when prior branch patterns subsume the current one, which implies their guard must have failed. We only do a trivial check that the prior pattern may have been the top pattern, but a more general thing would be to go through and say if `current - previous` is the empty, then `not` of the previous guard is `and` with our path. As we fold through we could keep a list of `(Pattern, Guard)` then we could compute that list easily to augment the path condition.

We should write tests that work similar to this example so each of the items that *should* have compiled show up as test failures, and then we should make a code change to make them work, and finally see them go green.

### PR DESCRIPTION
**Pull request by johnynek**
Resolved issue #1983 with compiler-side fixes and regression coverage.
- Updated `TypedExprRecursionCheck` to recognize direct top-level aliases to lowerable predef Int ops (e.g. `operator - = sub`), so infix recursive args now lower to SMT Int correctly.
- Added branch-path reasoning for guarded match fallthrough when a prior pattern subsumes the current one, even when the pattern itself is not directly lowerable. The checker now injects negated prior guard facts into later branch path conditions when safe.
- Kept existing fallthrough behavior and layered this logic into both normal `match` checking and `recur/loop` branch initialization.
- Added regression tests in `TypedExprRecursionCheckTest`:
  1) infix decrement via operator assignment alias (`operator - = sub`)
  2) negated guarded fallthrough from prior non-lowerable subsuming pattern.
- Reproduced both failures before the fix (both new tests failed), then verified they pass after the fix.
- Validation run: `sbt "coreJVM/testOnly dev.bosatsu.TypedExprRecursionCheckTest"` and required `scripts/test_basic.sh` (pass).

Fixes #1983

### CODE REVIEW

File: core/src/main/scala/dev/bosatsu/TypedExprRecursionCheck.scala [hunk 1]
```diff
@@ -1622,6 +1622,48 @@ object TypedExprRecursionCheck {
...
+        state: SmtBranchState
+    ): SmtBranchState =
+      // If a previous branch pattern fully covers the current pattern, falling
+      // through implies that prior guard was false.
+      priorBranches.foldLeft(state) { (st, priorBranch) =>
+        priorBranch.guard match {
+          case Some(guardExpr)
+              if patternSubsumes(priorBranch.pattern, currentPattern, st) =>
+            val guardFree = guardExpr.freeVarsDup.toSet
+            if (guardFree.subsetOf(availableBranchNames(currentPattern, st))) {
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/TypedExprRecursionCheck.scala]: There is mo guarantee the names refer to the same places in the pattern. We need some kind of alignment operation so that the bindings would mean the same thing.

I think this is currently dangerous. I'll try to write a failing test.
