### PR TITLE
Fix issue #2031: quantified apply fast-path leaked unbound type vars

### LINKED ISSUE #2031: Unknown var in normal construction
With this code:
```

from Bosatsu/Lazy import (
  Lazy,
  lazy,
)

enum VLazyList[a: +*]:
  Empty
  Cons(head: Lazy[a], tail: Lazy[VLazyList[a]])
  Mapped[b](source: VLazyList[b], fn: b -> a)

struct LazyList[a: +*](bound: Int, list: VLazyList[a]) 

empty_LazyList: forall a. LazyList[a] = LazyList(0, Empty)
lazy_empty: forall a. Lazy[LazyList[a]] = lazy(() -> empty_LazyList)
```

I get:

```
in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:44:43, package Zafu/Collection/LazyList
unknown var in a: unbound var: Bound(a) at [713, 739)
42|
43|empty_LazyList: forall a. LazyList[a] = LazyList(0, Empty)
44|lazy_empty: forall a. Lazy[LazyList[a]] = lazy(() -> empty_LazyList)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^


in file: /Users/oscar/code/zafu/src/Zafu/Collection/LazyList.bosatsu:44:54, package Zafu/Collection/LazyList
unknown var in a: unbound var: Bound(a) at [724, 738)
42|
43|empty_LazyList: forall a. LazyList[a] = LazyList(0, Empty)
44|lazy_empty: forall a. Lazy[LazyList[a]] = lazy(() -> empty_LazyList)
                                                        ^^^^^^^^^^^^^^
```
1. this could should work I think.
2. we should *never* have unbound var showing up in a type error to users
3. even if we did, this message shouldn't use the `toString` "Bound(a)"` and it is duplicative "unknown var in a: unbound var: Bound(a)".

I wonder if this could be an issue with instantiation. Since `Lazy` is covariant, we should have constructed: `Lazy[forall a. LazyList[a]]` since `empty_LazyList` is annotated (and that type checks).

### PR DESCRIPTION
**Pull request by johnynek**
Resolved issue #2031 by changing `Infer.checkApplyDom` so its direct-application instantiation fast-path is skipped when the expected result type has outer quantifiers (`forall`/`exists`). In the repro, that fast-path was checking arguments against types containing out-of-scope bound vars, producing `UnknownKindOfVar` errors like `Bound(a)` for valid code. The fallback path now handles this case correctly. I also tightened the internal error wording to avoid exposing `Bound(a)` formatting (`"unknown type variable ...: unbound variable"`). Added `core/src/test/scala/dev/bosatsu/Issue2031Test.scala` with the issue repro (using `Bosatsu/Lazy`) as a regression test that now passes. Ran required pre-push command `scripts/test_basic.sh` successfully (all CLI/core tests passed).

Fixes #2031

### CODE REVIEW

File: core/src/main/scala/dev/bosatsu/rankn/Infer.scala [hunk 1]
```diff
@@ -1821,57 +1821,61 @@ object Infer {
...
-
-          val subIn = inT.map(Type.substituteVar(_, instNoKind))
-          val fnName = functionNameHint(fn)
-
-          validKinds.parProductR {
-            val remainingFree =
-              NonEmptyList.fromList(
-                instantiation.frees.iterator.map { case (_, (k, b)) => (b, k) }.toList
-              )
+          val hasOuterQuantifiers =
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/rankn/Infer.scala]: can we move this up to the top of the method so that we can do this cheap check first, and not after we have done work?

But stepping back, we need to add a comment as to why
```
Type.instantiate(univ.iterator.toMap, outT, Map.empty, tpe, Map.empty)
```
succeeds, but then we can't use the result. A reader would naturally suspect that there is a bug lurking in instantiate or something else they don't understand.

Comment (johnynek) [reply core/src/main/scala/dev/bosatsu/rankn/Infer.scala]: Done. I moved the quantified-type guard to the top of `checkApplyDom` so we do the cheap check before `maybeSimple`/`instantiate`. I also added a comment explaining why `Type.instantiate(univ.iterator.toMap, outT, Map.empty, tpe, Map.empty)` can succeed but the fast path is still unsafe: the resulting substitutions can mention `tpe` quantifiers, while this path does not introduce those quantifiers into argument-checking scope, which is what caused the issue #2031 unbound-kind-variable failure. In that case we now intentionally defer to the fallback (`pure(None)`), which skolemizes before checking args.

**Comment by johnynek** [comment]
Applied the requested refactor/comment update in `core/src/main/scala/dev/bosatsu/rankn/Infer.scala` and re-ran the required pre-push check `scripts/test_basic.sh` successfully.
