### PR TITLE
Fix the scoping issue with top-level lets

### LINKED ISSUE #311: bug with incorrect shadowing of top-level bindings in Evaluation
below we exposed a serious bug in evaluation. if we make a closure over a top-level let binding and match on it like:
```
a = 42
f2 = match a:
  11: 10000
   x: x
```

we should expect f2 is 42, but if we do `eq_Int(f2, 11)` this winds up creating internal lambdas: `(\a -> eq_Int(f2, a))(11)` which overwrites the environment for f2.

I'm not 100% what is going on, but I think the problem is f2 is not carrying with it the fact that a is its environment so when it is evaluated in the context of `\a -> ...` the value for a overwrites.
 
I think this is due to the way we handle falling back to the top level...

```
runBosatsuTest(List("""package A

a = 42
f2 = match a:
  11: 12
   x: x

tests = Test("test record",
  [
    Assertion(f2.eq_Int(11), "f2 == 42"),
  ])
"""), "A", 1)
```

### PR DESCRIPTION
**Pull request by johnynek**
close #311

### CODE REVIEW

File: core/src/main/scala/org/bykn/bosatsu/Evaluation.scala [hunk 1]
```diff
@@ -230,6 +227,15 @@ object Evaluation {
...
       }
+
+    /**
+     * Top level Scoped objects have a fixed and known
+     * scope: that which is viewable at the top level
+     */
+    def withConstantEnv(env: => Env): Scoped = {
+      lazy val computedEnv = env
+      fromFn { _ => inEnv(computedEnv) }
+    }
```
Comment (johnynek) [inline core/src/main/scala/org/bykn/bosatsu/Evaluation.scala:238]: We could put the `inEnv(env)` call in the lazy val once.
