### PR TITLE
Fix #2082: avoid StackOverflowError in source-conversion type quantification

### LINKED ISSUE #2082: StackOverflowError in Expr.traverseType during SourceConverter.quantifyFrees on moderately large list literals
## Summary
`bosatsu lib check` can crash with `StackOverflowError` in `Expr.traverseType` when source-converting a moderately large expression (observed in zafu CI for PR #71).

## External Repro (Observed In CI)
- zafu PR: https://github.com/johnynek/zafu/pull/71
- failing job: https://github.com/johnynek/zafu/actions/runs/22834030066/job/66227314516
- command path: `scripts/test.sh` (`./bosatsu lib fetch && ./bosatsu lib check && ./bosatsu lib test`)
- tool binary fetched in CI: `bosatsu-linux` from release `v0.0.47`

The failure happens before test output (during compile/check), with stack frames repeating:

- `dev.bosatsu.Expr$.traverseType(Expr.scala:338)`
- `cats.data.NonEmptyList.traverse(NonEmptyList.scala:318)`
- `cats.data.WriterT.flatMap(...)`
- `cats.Eval...`

CI stack excerpt also includes `Expr.scala:330/338/354/358`, matching recursive traversal paths.

## Deterministic Repro In bosatsu Repo
I pushed a repro branch with a focused failing test:
- branch: `codex/repro-traversetype-stackoverflow`
- commit: `41658541b`
- file: `core/src/test/scala/dev/bosatsu/ExprTraverseTypeStackOverflowReproTest.scala`

Run:

```bash
sbt "coreJVM/testOnly dev.bosatsu.ExprTraverseTypeStackOverflowReproTest"
```

This test:
- constructs a source with a single top-level `tests = TestSuite(...)` whose list has ~200 `Assertion(...)` entries,
- runs `TestUtils.sourceConvertedProgramOf(...)` on a separate thread with a 256 KiB stack,
- currently fails with `StackOverflowError` and top frames in `Expr.traverseType` + `NonEmptyList.traverse` + `WriterT`.

## Diagnosis
The overflowing path is:

1. `SourceConverter.toProgram` top-level post-processing:
   - `SourceConverter.scala:2352` calls `Expr.quantifyFrees(e)` on top-level expressions.
2. `Expr.quantifyFrees`:
   - `Expr.scala:261-262`, calls `Expr.freeBoundTyVars(expr)`.
3. `Expr.freeBoundTyVars`:
   - `Expr.scala:401+`, uses `traverseType` with `Writer`.
4. `Expr.traverseType` recursion:
   - `Expr.scala:327-369`, especially `App` case (`args.traverse(...)` at line 338), produces deep `NonEmptyList.traverse` / `WriterT` / `Eval` stacks.

This appears stack-sensitive by environment: local macOS runs of zafu may pass, while Ubuntu native-image CI overflows.

## Expected
Source conversion/type traversal should be stack-safe for this input shape (or at least fail gracefully without JVM/native stack overflow).

### PR DESCRIPTION
**Pull request by johnynek**
Reproduced the reported failure by adding `ExprTraverseTypeStackOverflowReproTest` (small-stack thread + ~200 assertion list literal), which failed pre-fix with `StackOverflowError` in the `Expr.traverseType`/`Writer` path from `SourceConverter.scala:2352`.

Implemented an iterative `Expr.freeBoundTyVars` using an explicit work stack over `Expr`, branch `Pattern`, and `Type` nodes, preserving traversal order while removing recursion from the hot path used by `Expr.quantifyFrees`. Kept the previous traversal implementation as `freeBoundTyVarsViaTraverseType` as an oracle.

Added regression coverage:
- `ExprTraverseTypeStackOverflowReproTest`: verifies source conversion no longer overflows on a 256 KiB stack.
- `ExprTest`: new property test asserting `freeBoundTyVars` matches `freeBoundTyVarsViaTraverseType`.

Validation run:
- `sbt "coreJVM/testOnly dev.bosatsu.ExprTraverseTypeStackOverflowReproTest"` (fails before fix, passes after)
- `sbt "coreJVM/testOnly dev.bosatsu.ExprTest"`
- `sbt "coreJVM/testOnly dev.bosatsu.codegen.clang.ClangGenTest -- --log=failure"`
- `scripts/test_basic.sh` (pass: `Total 62, Failed 0`).

Fixes #2082

### CODE REVIEW

File: core/src/main/scala/dev/bosatsu/Expr.scala [hunk 1]
```diff
@@ -395,16 +395,118 @@ object Expr {
     }
   }
 
-  // Returns a distinct list of free bound type variables
-  // in the order they were encountered in traversal
-  def freeBoundTyVars[A](expr: Expr[A]): List[Type.Var.Bound] = {
+  // Oracle implementation used for testing optimized implementations.
+  private[bosatsu] def freeBoundTyVarsViaTraverseType[A](
```
Comment (johnynek) [inline core/src/main/scala/dev/bosatsu/Expr.scala]: move this to the test code.

Comment (johnynek) [reply core/src/main/scala/dev/bosatsu/Expr.scala]: Done. I removed `freeBoundTyVarsViaTraverseType` from production `Expr.scala` and moved the traverseType-based oracle into `ExprTest` as private test helpers (`traverseTypeOracle` + `freeBoundTyVarsViaTraverseType`). The property assertion now uses the test-local oracle, so the equivalence check remains in test code only.

**Comment by johnynek** [comment]
Implemented the requested move to test-only code and reran checks:
- `sbt "coreJVM/testOnly dev.bosatsu.ExprTest dev.bosatsu.ExprTraverseTypeStackOverflowReproTest"`
- `scripts/test_basic.sh` (pass: `Total 62, Failed 0`).
